// AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
// Generated by scripts/generate_ultra.py — 2026-02-23T01:58:02Z

import { PuzzleSpec, WordPlacement } from '../puzzleBuilder';

export const ch121: PuzzleSpec = {
    id: 'ch121',
    title: 'İz Sürücü',
    rows: 6,
    cols: 6,
    theme: 'Genel',
    difficulty: 'easy',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Antlaşma, sözleşme; dönem', answer: 'AHİT' },
        { clueRow: 4, clueCol: 0, direction: 'across', clue: 'Fransa\'nın başkenti', answer: 'PARİS' },
        { clueRow: 1, clueCol: 1, direction: 'down', clue: 'Biranın hammaddesi veya atın yeyip coştuğu tahıl vb ürün yemi', answer: 'ARPA' },
        { clueRow: 0, clueCol: 3, direction: 'down', clue: 'Cömert olmayan, parasını harcamaktan çekinen pinti', answer: 'CİMRİ' },
        { clueRow: 0, clueCol: 5, direction: 'down', clue: 'Kâr ya da şirketten veya pastadan düşen her parçevi pay', answer: 'HİSSE' }
    ],
};

export const ch122: PuzzleSpec = {
    id: 'ch122',
    title: 'Altın Kapı',
    rows: 6,
    cols: 6,
    theme: 'Genel',
    difficulty: 'easy',
    placements: [
        { clueRow: 1, clueCol: 0, direction: 'across', clue: 'Besin tüketmek', answer: 'YEMEK' },
        { clueRow: 3, clueCol: 0, direction: 'across', clue: 'Gerekli (dini)', answer: 'VACİP' },
        { clueRow: 0, clueCol: 1, direction: 'down', clue: 'Hızlı olmayan, ağır hareket eden', answer: 'YAVAŞ' },
        { clueRow: 0, clueCol: 3, direction: 'down', clue: 'Diş fırçasının üstüne sıkılan temizleyici sıvı-katı karışım', answer: 'MACUN' },
        { clueRow: 0, clueCol: 5, direction: 'down', clue: 'İnsanın en sadık dostu', answer: 'KÖPEK' }
    ],
};

export const ch123: PuzzleSpec = {
    id: 'ch123',
    title: 'Gizli Hazine',
    rows: 6,
    cols: 6,
    theme: 'Genel',
    difficulty: 'easy',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Bir görev, veya yer için seçilip göreve talip olan kişi', answer: 'ADAY' },
        { clueRow: 4, clueCol: 0, direction: 'across', clue: 'Sinema filminde veya tiyatro ekibinde erkek oyuncu', answer: 'AKTÖR' },
        { clueRow: 1, clueCol: 1, direction: 'down', clue: 'Tanrı\'ya verilen söz, nezir', answer: 'ADAK' },
        { clueRow: 0, clueCol: 3, direction: 'down', clue: 'Erkek ve kadınların dize ya daha alta inen kalın yünlü kaşe kalın dış kapaması ceketlik', answer: 'PALTO' },
        { clueRow: 0, clueCol: 5, direction: 'down', clue: 'Sözlerinin bütünü müzikli şarkı formunda söylenen yüksek sesli büyük sahne gösterisi (5H)', answer: 'OPERA' }
    ],
};

export const ch124: PuzzleSpec = {
    id: 'ch124',
    title: 'Ufuk Çizgisi',
    rows: 6,
    cols: 6,
    theme: 'Genel',
    difficulty: 'easy',
    placements: [
        { clueRow: 1, clueCol: 0, direction: 'across', clue: 'Karadenizlilerin vazgeçilmezi küçük balık', answer: 'HAMSİ' },
        { clueRow: 3, clueCol: 0, direction: 'across', clue: 'Geçimi zor olan, yoksul kimse', answer: 'FAKİR' },
        { clueRow: 0, clueCol: 1, direction: 'down', clue: 'Kaldırması kolay, çok az çeken', answer: 'HAFİF' },
        { clueRow: 0, clueCol: 3, direction: 'down', clue: 'Kumaş veya kağıt kesmek için kullanılan ortadan perçinli iki bıçak yüzlü alet', answer: 'MAKAS' },
        { clueRow: 0, clueCol: 5, direction: 'down', clue: 'Uyulması veya kaçınılması gereken kıssadan hisse çıkarılan acı ders', answer: 'İBRET' }
    ],
};

export const ch125: PuzzleSpec = {
    id: 'ch125',
    title: 'Yıldız Avcısı',
    rows: 6,
    cols: 6,
    theme: 'Genel',
    difficulty: 'easy',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Gerek, lazım gelme', answer: 'İCAP' },
        { clueRow: 4, clueCol: 0, direction: 'across', clue: 'Peşin para', answer: 'NAKİT' },
        { clueRow: 1, clueCol: 1, direction: 'down', clue: 'Ucundan ip geçirip dikiş yapmaya yarayan ince sivri çelik araç', answer: 'İĞNE' },
        { clueRow: 0, clueCol: 3, direction: 'down', clue: 'Para yatırıp çekilen mevduat kredi finans kurumu', answer: 'BANKA' },
        { clueRow: 0, clueCol: 5, direction: 'down', clue: 'Yazıda cümlenin sonuna konulan pıtrak işaret', answer: 'NOKTA' }
    ],
};

export const ch126: PuzzleSpec = {
    id: 'ch126',
    title: 'Güçlü Eller',
    rows: 7,
    cols: 7,
    theme: 'Genel',
    difficulty: 'easy',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Ad, nam (okunmamak)', answer: 'ESAME' },
        { clueRow: 4, clueCol: 0, direction: 'across', clue: 'Kalın ve uzun enli geniş kaba kerestre falan odundan işlenmiş kalıp sarmal dikme vb kalas odun (5)', answer: 'KALAS' },
        { clueRow: 6, clueCol: 0, direction: 'across', clue: 'Anasonla tatlandırılmış, su katılınca beyazlaşan içki', answer: 'RAKI' },
        { clueRow: 1, clueCol: 1, direction: 'down', clue: 'Fikirler, tasa', answer: 'EFKAR' },
        { clueRow: 1, clueCol: 3, direction: 'down', clue: 'Toplumda iyilik ve vs üzerine kurulmuş vicdani vs kural seti edep etiği (5)', answer: 'AHLAK' },
        { clueRow: 0, clueCol: 5, direction: 'down', clue: 'Boyalar ve fırçayla tuval üzerine resim yapan sanatçı', answer: 'RESSAM' }
    ],
};

export const ch127: PuzzleSpec = {
    id: 'ch127',
    title: 'Derin Kökleri',
    rows: 7,
    cols: 7,
    theme: 'Genel',
    difficulty: 'easy',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Sebep bildiri', answer: 'ÇÜNKÜ' },
        { clueRow: 4, clueCol: 0, direction: 'across', clue: 'Bölüm, parça', answer: 'KISIM' },
        { clueRow: 6, clueCol: 0, direction: 'across', clue: 'Toplumsal şiddet', answer: 'LİNÇ' },
        { clueRow: 1, clueCol: 1, direction: 'down', clue: 'Tilki ile kurt arası yırtıcı bir yaban hayvanı', answer: 'ÇAKAL' },
        { clueRow: 1, clueCol: 3, direction: 'down', clue: '23 ... Ulusal Egemenlik ve Çocuk Bayramı kutlanan ay', answer: 'NİSAN' },
        { clueRow: 0, clueCol: 5, direction: 'down', clue: 'Saygı, riayet', answer: 'HÜRMET' }
    ],
};

export const ch128: PuzzleSpec = {
    id: 'ch128',
    title: 'Rüzgar Gülü',
    rows: 7,
    cols: 7,
    theme: 'Genel',
    difficulty: 'easy',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Gece (Arapça)', answer: 'LEYLA' },
        { clueRow: 4, clueCol: 0, direction: 'across', clue: 'Madde ve enerjinin doğadaki etkileşimini inceleyen bilim dalı', answer: 'FİZİK' },
        { clueRow: 6, clueCol: 0, direction: 'across', clue: 'Uykudayken irenç veya güzel zihinde vizyon edilen düş (4 HRf)', answer: 'RÜYA' },
        { clueRow: 1, clueCol: 1, direction: 'down', clue: 'Denizin dişli ve saldırgan lezzetli balığı', answer: 'LÜFER' },
        { clueRow: 1, clueCol: 3, direction: 'down', clue: 'Cismin en dış kısmı, satıh', answer: 'YÜZEY' },
        { clueRow: 0, clueCol: 5, direction: 'down', clue: 'Ev çıkıntısı', answer: 'BALKON' }
    ],
};

export const ch129: PuzzleSpec = {
    id: 'ch129',
    title: 'Demir Yürek',
    rows: 7,
    cols: 7,
    theme: 'Genel',
    difficulty: 'easy',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Midenin bulundu göğüs ile kasık arası vücut bölgesi', answer: 'KARIN' },
        { clueRow: 4, clueCol: 0, direction: 'across', clue: 'Olayların geçtiği süre, vakit', answer: 'ZAMAN' },
        { clueRow: 6, clueCol: 0, direction: 'across', clue: 'Casus', answer: 'AJAN' },
        { clueRow: 1, clueCol: 1, direction: 'down', clue: 'Toprak aleti', answer: 'KAZMA' },
        { clueRow: 1, clueCol: 3, direction: 'down', clue: 'Eğimli yol', answer: 'RAMPA' },
        { clueRow: 0, clueCol: 5, direction: 'down', clue: 'Dışı pullu sert zırhlı sarımsı tropikal kokulu güzel lezzet', answer: 'ANANAS' }
    ],
};

export const ch130: PuzzleSpec = {
    id: 'ch130',
    title: 'Ateş Kıvılcımı',
    rows: 7,
    cols: 7,
    theme: 'Genel',
    difficulty: 'easy',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Tanrı sevgisiyle kendinden geçme', answer: 'CEZBE' },
        { clueRow: 4, clueCol: 0, direction: 'across', clue: 'En üst', answer: 'ZİRVE' },
        { clueRow: 6, clueCol: 0, direction: 'across', clue: 'Boyutlar, büyüklük', answer: 'EBAT' },
        { clueRow: 1, clueCol: 1, direction: 'down', clue: 'Türk kahvesini köpürtmek için dar alanlı kulplu uzun kahve pişireciği', answer: 'CEZVE' },
        { clueRow: 1, clueCol: 3, direction: 'down', clue: 'Cebren', answer: 'ZORLA' },
        { clueRow: 0, clueCol: 5, direction: 'down', clue: 'Göktaşı', answer: 'METEOR' }
    ],
};

export const ch131: PuzzleSpec = {
    id: 'ch131',
    title: 'Su Altı',
    rows: 8,
    cols: 8,
    theme: 'Genel',
    difficulty: 'medium',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Tramvay süren görevli', answer: 'VATMAN' },
        { clueRow: 4, clueCol: 0, direction: 'across', clue: 'Saat tamircisi', answer: 'SAATÇİ' },
        { clueRow: 6, clueCol: 0, direction: 'across', clue: 'İlerleyip gitme', answer: 'GEÇME' },
        { clueRow: 7, clueCol: 0, direction: 'across', clue: 'Yeraltı geçidi', answer: 'TÜNEL' },
        { clueRow: 1, clueCol: 2, direction: 'down', clue: 'Hazır', answer: 'AMADE' },
        { clueRow: 1, clueCol: 4, direction: 'down', clue: 'Cs f vs ns ( 5 as fs ) ( MATEMATİK= 9 Harf olmaz = MATA =4 OLMAZ= GEOM  OLMAZ )', answer: 'MATEM' },
        { clueRow: 0, clueCol: 6, direction: 'down', clue: 'Patlama', answer: 'İNFİLAK' }
    ],
};

export const ch132: PuzzleSpec = {
    id: 'ch132',
    title: 'Köpük Sesi',
    rows: 8,
    cols: 8,
    theme: 'Genel',
    difficulty: 'medium',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Dijitaldeki yazıyı veya resmi kağıda basan makine', answer: 'YAZICI' },
        { clueRow: 4, clueCol: 0, direction: 'across', clue: 'Turuncu renkli, tek çekirdekli, tatlı yaz meyvesi', answer: 'KAYISI' },
        { clueRow: 6, clueCol: 0, direction: 'across', clue: 'Evlilik kararı alan çiftlerin yüzük taktığı tören', answer: 'NİŞAN' },
        { clueRow: 7, clueCol: 0, direction: 'across', clue: 'Uçak veya helikopteri uçuran sürücü kişi', answer: 'PİLOT' },
        { clueRow: 1, clueCol: 2, direction: 'down', clue: 'Sinirli', answer: 'ASABİ' },
        { clueRow: 1, clueCol: 4, direction: 'down', clue: 'Sıcak fışkıran şifalı maden suyu, kaplıca', answer: 'ILICA' },
        { clueRow: 0, clueCol: 6, direction: 'down', clue: 'Ekmek yapıp satan esnaf', answer: 'FIRINCI' }
    ],
};

export const ch133: PuzzleSpec = {
    id: 'ch133',
    title: 'Mavi Uçurum',
    rows: 8,
    cols: 8,
    theme: 'Genel',
    difficulty: 'medium',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'İpliğin sarıldığı ortası delik yuvarlak döner kasnak', answer: 'MAKARA' },
        { clueRow: 4, clueCol: 0, direction: 'across', clue: 'Bir yerden ayrılmak', answer: 'GİTMEK' },
        { clueRow: 6, clueCol: 0, direction: 'across', clue: 'Olabilir', answer: 'BELKİ' },
        { clueRow: 7, clueCol: 0, direction: 'across', clue: 'Orduya mensup vatan koruyucusu er', answer: 'ASKER' },
        { clueRow: 1, clueCol: 2, direction: 'down', clue: 'İnanç esası veya şeker', answer: 'AKİDE' },
        { clueRow: 1, clueCol: 4, direction: 'down', clue: 'Bir şeyi elle tutup kendine geçirmek veya parayla satın edinmek', answer: 'ALMAK' },
        { clueRow: 0, clueCol: 6, direction: 'down', clue: 'Gürültülü ve yüksek sesle atılan neşeli gülüş', answer: 'KAHKAHA' }
    ],
};

export const ch134: PuzzleSpec = {
    id: 'ch134',
    title: 'Mercan Bahçesi',
    rows: 8,
    cols: 8,
    theme: 'Genel',
    difficulty: 'medium',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Halk topluluğu', answer: 'CUMHUR' },
        { clueRow: 4, clueCol: 0, direction: 'across', clue: 'Yoksullara yemek verilen yer', answer: 'İMARET' },
        { clueRow: 6, clueCol: 0, direction: 'across', clue: 'Saklamayıp söyleme', answer: 'İKRAR' },
        { clueRow: 7, clueCol: 0, direction: 'across', clue: 'Sağlığını koruyamamış rahatsız', answer: 'HASTA' },
        { clueRow: 1, clueCol: 2, direction: 'down', clue: 'Havada kanatlarla havalanıp ilerleme hareketi(kuş gibi vb)', answer: 'UÇMAK' },
        { clueRow: 1, clueCol: 4, direction: 'down', clue: 'Kazaktan farklı ki önünden düğmeli ve açık olarak giyilip fermuar veya ip olan üstlük triko /örgü', answer: 'HIRKA' },
        { clueRow: 0, clueCol: 6, direction: 'down', clue: 'İmalatla yeni bir ürün elde etmek', answer: 'ÜRETMEK' }
    ],
};

export const ch135: PuzzleSpec = {
    id: 'ch135',
    title: 'Dalgalar Ötesi',
    rows: 8,
    cols: 8,
    theme: 'Genel',
    difficulty: 'medium',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Saygınlık', answer: 'İTİBAR' },
        { clueRow: 4, clueCol: 0, direction: 'across', clue: 'Yılın on ikinci ve son ayı', answer: 'ARALIK' },
        { clueRow: 6, clueCol: 0, direction: 'across', clue: 'Giyim ve (...)\'ın eş eki gibi, donanma giysi tertip giyim kuşam diyerek beraber kullanılan ek söz', answer: 'KUŞAM' },
        { clueRow: 7, clueCol: 0, direction: 'across', clue: 'Yaşamsal enerjisi ve metabolizması çalışan ve devinen bitki vb organizma', answer: 'CANLI' },
        { clueRow: 1, clueCol: 2, direction: 'down', clue: 'Çökelti', answer: 'TORTU' },
        { clueRow: 1, clueCol: 4, direction: 'down', clue: 'Acs d b m db v xs gb cx db fb ms hb k ms g ns ) BLatS s f nd bf b) = BALtA : 5 hr as vb d g ns', answer: 'BALTA' },
        { clueRow: 0, clueCol: 6, direction: 'down', clue: 'Tarla ve bahçe işlerinde kullanılan güçlü motorlu araç', answer: 'TRAKTÖR' }
    ],
};

export const ch136: PuzzleSpec = {
    id: 'ch136',
    title: 'Sarp Yol',
    rows: 9,
    cols: 9,
    theme: 'Genel',
    difficulty: 'medium',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Üzeri susamlı sabah çayının vazgeçilmezi halka şeklindeki ekmek türü', answer: 'SİMİT' },
        { clueRow: 5, clueCol: 0, direction: 'across', clue: 'Ege bölgesinde çok yetişen bol çekirdekli tatlı meyve', answer: 'İNCİR' },
        { clueRow: 7, clueCol: 2, direction: 'across', clue: 'Sıvı akışını kesen musluk', answer: 'VANA' },
        { clueRow: 8, clueCol: 0, direction: 'across', clue: 'Uyma, itaat', answer: 'RİAYET' },
        { clueRow: 1, clueCol: 2, direction: 'down', clue: 'Anlayış, terbiye', answer: 'İZAN' },
        { clueRow: 1, clueCol: 4, direction: 'down', clue: 'Birine suç yükleme, kara çalma', answer: 'İFTİRA' },
        { clueRow: 6, clueCol: 6, direction: 'down', clue: 'Binek ve yük hayvanı olarak kullanılan, yeleli ve kuyruklu hayvan', answer: 'AT' }
    ],
};

export const ch137: PuzzleSpec = {
    id: 'ch137',
    title: 'Granit Zihin',
    rows: 9,
    cols: 9,
    theme: 'Genel',
    difficulty: 'medium',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Kulaklarının ucunda tüyleri olan Anadolu\'da da nesli olan güçlü yaban kedisi', answer: 'VAŞAK' },
        { clueRow: 5, clueCol: 0, direction: 'across', clue: 'Siyah ve beyaz çizgili Afrika atı', answer: 'ZEBRA' },
        { clueRow: 7, clueCol: 2, direction: 'across', clue: 'Dolaba tıkmadan omuzlarından demir pılasdik tel çengele asıp dolaba vurduğumuz asacak', answer: 'ASKI' },
        { clueRow: 8, clueCol: 0, direction: 'across', clue: 'Peygamberin yaptıkları', answer: 'SÜNNET' },
        { clueRow: 1, clueCol: 2, direction: 'down', clue: 'Anne baba ve çocukların oluşturduğu toplumun en küçük sosyal yuva direği yapıtaşı (4)', answer: 'AİLE' },
        { clueRow: 1, clueCol: 4, direction: 'down', clue: 'Sinema ve sahnede dramatik sahneye hayat katıp şov yapan kadın sanatçı', answer: 'AKTRİS' },
        { clueRow: 6, clueCol: 6, direction: 'down', clue: 'Köpek (halk ağzı)', answer: 'IT' }
    ],
};

export const ch138: PuzzleSpec = {
    id: 'ch138',
    title: 'Kaya Parçası',
    rows: 9,
    cols: 9,
    theme: 'Genel',
    difficulty: 'medium',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Esir olmayan, hür, kendi iradesiyle karar veren (....lük vs değil kökü)', answer: 'ÖZGÜR' },
        { clueRow: 5, clueCol: 0, direction: 'across', clue: 'Bebekleri uyutmak için söylenen türkü', answer: 'NİNNİ' },
        { clueRow: 7, clueCol: 2, direction: 'across', clue: 'Ufak tefek çikolata tost bisküvi gibi hazır büfeden gazete veren ufak kulübe yeme içme işletimi', answer: 'BÜFE' },
        { clueRow: 8, clueCol: 0, direction: 'across', clue: 'Sütün laktik asit fermantasyonuyla elde edilen besin', answer: 'YOĞURT' },
        { clueRow: 1, clueCol: 2, direction: 'down', clue: 'Aklı çabuk kavrayan, anlama yetisi yüksek olan', answer: 'ZEKİ' },
        { clueRow: 1, clueCol: 4, direction: 'down', clue: 'Olumsuz olayların hissettirdiği keder, gam', answer: 'ÜZÜNTÜ' },
        { clueRow: 6, clueCol: 6, direction: 'down', clue: 'Kasaplık hayvanlardan sağlanan kas dokusu; yiyecek', answer: 'ET' }
    ],
};

export const ch139: PuzzleSpec = {
    id: 'ch139',
    title: 'Taş ve Rüzgar',
    rows: 9,
    cols: 9,
    theme: 'Genel',
    difficulty: 'medium',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Kumaş vb dikmek için kullanılan ince katlı tel, ip', answer: 'İPLİK' },
        { clueRow: 5, clueCol: 0, direction: 'across', clue: 'Tiyatro gösterisi yapılan yüksekçe yer', answer: 'SAHNE' },
        { clueRow: 7, clueCol: 2, direction: 'across', clue: 'Annenin veya babanın annesi', answer: 'NİNE' },
        { clueRow: 8, clueCol: 0, direction: 'across', clue: 'Tavuğun yumurtadan yeni çıkmış sarı paytak ve sevimli yavrusu', answer: 'CİVCİV' },
        { clueRow: 1, clueCol: 2, direction: 'down', clue: 'Kuzey Amerika\'nın gri veya dumanlı rengindeki büyük ve seri dağ aslanı (jaguar değl)', answer: 'PUMA' },
        { clueRow: 1, clueCol: 4, direction: 'down', clue: 'Öğle ile akşam arasındaki süre', answer: 'İKİNDİ' },
        { clueRow: 6, clueCol: 6, direction: 'down', clue: 'İçinde yaşanılan bina, konut', answer: 'EV' }
    ],
};

export const ch140: PuzzleSpec = {
    id: 'ch140',
    title: 'Dağ Kartalı',
    rows: 9,
    cols: 9,
    theme: 'Genel',
    difficulty: 'medium',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Ağzın girişindeki kızarık etli üst ve altı kapatan iki örtü parçası et', answer: 'DUDAK' },
        { clueRow: 5, clueCol: 0, direction: 'across', clue: 'Hakkından gelmek vb yapışık değil 3lü kelime. HAK YAP.', answer: 'HAKLA' },
        { clueRow: 7, clueCol: 2, direction: 'across', clue: 'Geriye sürme', answer: 'İTME' },
        { clueRow: 8, clueCol: 0, direction: 'across', clue: 'Yıldızların, duman ve gazların kütle çekimle toplandığı sistem, gökada (Galaksi TR)', answer: 'GALAXY' },
        { clueRow: 1, clueCol: 2, direction: 'down', clue: 'Çiğ köftesiyle meşhur şanlı ünvanlı ilimiz', answer: 'URFA' },
        { clueRow: 1, clueCol: 4, direction: 'down', clue: 'Tembellik, eylemsizlik', answer: 'ATALET' },
        { clueRow: 6, clueCol: 6, direction: 'down', clue: 'Seslenme sözü', answer: 'EY' }
    ],
};

export const ch141: PuzzleSpec = {
    id: 'ch141',
    title: 'Şimşek Hızı',
    rows: 10,
    cols: 10,
    theme: 'Genel',
    difficulty: 'medium',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Meyve suyu ile şekerli sudan yapılan içecek', answer: 'ŞERBET' },
        { clueRow: 5, clueCol: 0, direction: 'across', clue: 'Meksika kökenli bedeni titreye titreye öfkelenen minyatur iriliği olan kulaklı köpek', answer: 'ÇİVAVA' },
        { clueRow: 8, clueCol: 2, direction: 'across', clue: 'Isısı düşük olan, üşüten', answer: 'SOĞUK' },
        { clueRow: 9, clueCol: 0, direction: 'across', clue: 'Kısmeti (çekim)', answer: 'KISMETİ' },
        { clueRow: 1, clueCol: 2, direction: 'down', clue: 'Doğru olmayan eğik ya da kıvrımlı sapan şaşmış eksenli', answer: 'EĞRİ' },
        { clueRow: 1, clueCol: 4, direction: 'down', clue: 'Delikli ve deliksiz oynananı olan çuhalı masa sporu', answer: 'BİLARDO' },
        { clueRow: 7, clueCol: 7, direction: 'down', clue: 'İlgi zamiri veya bağlaç', answer: 'Kİ' }
    ],
};

export const ch142: PuzzleSpec = {
    id: 'ch142',
    title: 'Elektrik Rüzgar',
    rows: 10,
    cols: 10,
    theme: 'Genel',
    difficulty: 'medium',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Elin ucundaki 5 uzun organ', answer: 'PARMAK' },
        { clueRow: 5, clueCol: 0, direction: 'across', clue: 'Okuma (Kuran)', answer: 'KIRAAT' },
        { clueRow: 8, clueCol: 2, direction: 'across', clue: 'Spikerin ekranda duyurduğu flaş olay gazetelerin baş puntolu manşeti (vecihi)', answer: 'HABER' },
        { clueRow: 9, clueCol: 0, direction: 'across', clue: 'Hoşça vakit geçirme, neşelenme faaliyeti', answer: 'EĞLENCE' },
        { clueRow: 1, clueCol: 2, direction: 'down', clue: 'Kışın soğuktan boynu sarmak için kullanılan uzun örgü kumaş', answer: 'ATKI' },
        { clueRow: 1, clueCol: 4, direction: 'down', clue: 'Dereceye girenlere verilen altın gümüş bronz ödül rozeti', answer: 'MADALYA' },
        { clueRow: 7, clueCol: 7, direction: 'down', clue: 'Bir nota', answer: 'RE' }
    ],
};

export const ch143: PuzzleSpec = {
    id: 'ch143',
    title: 'Fırtına Gözü',
    rows: 10,
    cols: 10,
    theme: 'Genel',
    difficulty: 'medium',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Oyun, dizi veya filmde rol alan veya bir sporu oynayan kişi', answer: 'OYUNCU' },
        { clueRow: 5, clueCol: 0, direction: 'across', clue: 'Şa evi; Şa yapılan yer', answer: 'ŞAHANE' },
        { clueRow: 8, clueCol: 2, direction: 'across', clue: 'Kırkayak benzeri ama zehirli ısıran korkutucu ve yassı ebatlı seri eklem bacaklı orman canlısı', answer: 'ÇIYAN' },
        { clueRow: 9, clueCol: 0, direction: 'across', clue: 'Kralın karısına yada bizzat tahtta oturan kadın hükümdara verilen isim ünvanı (7)', answer: 'KRALİÇE' },
        { clueRow: 1, clueCol: 2, direction: 'down', clue: 'Yürüyen', answer: 'YAYA' },
        { clueRow: 1, clueCol: 4, direction: 'down', clue: 'Evlilik yolunda yüzük takmış olan sözlü kişiler', answer: 'NİŞANLI' },
        { clueRow: 7, clueCol: 7, direction: 'down', clue: 'Hangi şey?', answer: 'NE' }
    ],
};

export const ch144: PuzzleSpec = {
    id: 'ch144',
    title: 'Işık Hızı',
    rows: 10,
    cols: 10,
    theme: 'Genel',
    difficulty: 'medium',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Çiçeklerden süzülen meyvenin özündeki lezzetli şemsi su/sıvı, arıların topladığı şerbet', answer: 'NEKTAR' },
        { clueRow: 5, clueCol: 0, direction: 'across', clue: 'Yaya asker', answer: 'PİYADE' },
        { clueRow: 8, clueCol: 2, direction: 'across', clue: 'Bankadan borç olarak çekilen geri ödemeli para tutarı', answer: 'KREDİ' },
        { clueRow: 9, clueCol: 0, direction: 'across', clue: 'Devletin yönetim merkezinin bulunduğu şehir', answer: 'BAŞKENT' },
        { clueRow: 1, clueCol: 2, direction: 'down', clue: 'Kardeş eşlerinin birbirine göre durumu ve akrabalığı', answer: 'ELTİ' },
        { clueRow: 1, clueCol: 4, direction: 'down', clue: 'Çoğalma', answer: 'TEKASÜR' },
        { clueRow: 7, clueCol: 7, direction: 'down', clue: 'Köpek (kaba tabir)', answer: 'İT' }
    ],
};

export const ch145: PuzzleSpec = {
    id: 'ch145',
    title: 'Yıldırım Bilek',
    rows: 10,
    cols: 10,
    theme: 'Genel',
    difficulty: 'medium',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Uzak nesneleri yakın gösteren optik alet', answer: 'DÜRBÜN' },
        { clueRow: 5, clueCol: 0, direction: 'across', clue: 'Suyun yüksek bir yerden coşkuyla döküldüğü yer', answer: 'ŞELALE' },
        { clueRow: 8, clueCol: 2, direction: 'across', clue: 'Amerika ve Avrupa Afrika arasındaki kocaman okyanus (veya coğrafya harita kitabı)', answer: 'ATLAS' },
        { clueRow: 9, clueCol: 0, direction: 'across', clue: 'Yavrularını kesesinde taşıyan sıçrayıcı Avustralya hayvanı', answer: 'KANGURU' },
        { clueRow: 1, clueCol: 2, direction: 'down', clue: 'Devletin hüküm sürdüğü sınırlarla çevrili memleket', answer: 'ÜLKE' },
        { clueRow: 1, clueCol: 4, direction: 'down', clue: 'Yemeğe lezzet kokla tat katmak için tohumlardan köklerden alınan kurutulmuş toz çeşni (kimyon, vb)', answer: 'BAHARAT' },
        { clueRow: 7, clueCol: 7, direction: 'down', clue: 'Rengi, kokusu ve tadı olmayan, canlıların yaşaması için şart olan sıvı', answer: 'SU' }
    ],
};

export const ch146: PuzzleSpec = {
    id: 'ch146',
    title: 'Ejderha Yolu',
    rows: 11,
    cols: 11,
    theme: 'Genel',
    difficulty: 'hard',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Saygı', answer: 'İHTİRAM' },
        { clueRow: 5, clueCol: 0, direction: 'across', clue: 'Osmanlı\'da devleti tek başına yöneten tahtlı sultana verilen ulu büyük unvan (7)', answer: 'PADİŞAH' },
        { clueRow: 9, clueCol: 2, direction: 'across', clue: 'Tarım', answer: 'ZİRAAT' },
        { clueRow: 10, clueCol: 0, direction: 'across', clue: 'Buz ve tozdan oluşan arkasından toz bulutu saçan yıldız (Halley vb.) (____ Yıldız)', answer: 'KUYRUKLU' },
        { clueRow: 1, clueCol: 2, direction: 'down', clue: 'Tuvaletin eski halk ağzındaki çokca söylenen kısa basit dilli halk adı (Hela vb )', answer: 'HELA' },
        { clueRow: 1, clueCol: 4, direction: 'down', clue: 'Patlama (çekim)', answer: 'İNFİLAKİ' },
        { clueRow: 8, clueCol: 8, direction: 'down', clue: 'Yuhalama sesi', answer: 'TU' }
    ],
};

export const ch147: PuzzleSpec = {
    id: 'ch147',
    title: 'Ateş Nefesi',
    rows: 11,
    cols: 11,
    theme: 'Genel',
    difficulty: 'hard',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Hoşa giden, insanda sevgi uyandıran sempatik (7)', answer: 'SEVİMLİ' },
        { clueRow: 5, clueCol: 0, direction: 'across', clue: 'Dış alım', answer: 'İTHALAT' },
        { clueRow: 9, clueCol: 2, direction: 'across', clue: 'Kaygı', answer: 'ENDİŞE' },
        { clueRow: 10, clueCol: 0, direction: 'across', clue: 'Denetçi', answer: 'MÜFETTİŞ' },
        { clueRow: 1, clueCol: 2, direction: 'down', clue: 'Olumlu cevap, onaylama sözü', answer: 'EVET' },
        { clueRow: 1, clueCol: 4, direction: 'down', clue: 'Trenlerin durduğu ve kalktığı yer, gar', answer: 'İSTASYON' },
        { clueRow: 8, clueCol: 8, direction: 'down', clue: 'Karı koca biri; benzer', answer: 'EŞ' }
    ],
};

export const ch148: PuzzleSpec = {
    id: 'ch148',
    title: 'Kanatlar',
    rows: 11,
    cols: 11,
    theme: 'Genel',
    difficulty: 'hard',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Kayısı diyarı', answer: 'MALATYA' },
        { clueRow: 5, clueCol: 0, direction: 'across', clue: 'Kafeste beslenen ince güzel sesli sarı evcil kuş', answer: 'KANARYA' },
        { clueRow: 9, clueCol: 2, direction: 'across', clue: 'Oturma, yerleşme', answer: 'İKAMET' },
        { clueRow: 10, clueCol: 0, direction: 'across', clue: 'İl, ilçe gibi yerleşim yerlerinde yerel hizmetleri gören idare', answer: 'BELEDİYE' },
        { clueRow: 1, clueCol: 2, direction: 'down', clue: 'Dünyanın en geniş ve kalabalık toprağı olan kıta', answer: 'ASYA' },
        { clueRow: 1, clueCol: 4, direction: 'down', clue: 'Kavratmak hikaye vb olayları başkasına birbiriyle söyleme sunma eylemi', answer: 'ANLATMAK' },
        { clueRow: 8, clueCol: 8, direction: 'down', clue: 'Arap alfabesi harfi', answer: 'TE' }
    ],
};

export const ch149: PuzzleSpec = {
    id: 'ch149',
    title: 'Pençe',
    rows: 11,
    cols: 11,
    theme: 'Genel',
    difficulty: 'hard',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Ele veya kollara geçirilen madeni süs veya altın takı', answer: 'BİLEZİK' },
        { clueRow: 5, clueCol: 0, direction: 'across', clue: 'Demiri ocakta kızdırıp döverek şekillendiren kişi', answer: 'DEMİRCİ' },
        { clueRow: 9, clueCol: 2, direction: 'across', clue: 'Bir işin veya durumun sonu, netice', answer: 'AKIBET' },
        { clueRow: 10, clueCol: 0, direction: 'across', clue: 'Kaynar sıvı yağın içine atılarak pişirilen çıtır patates veya sebze yemeği tarifi', answer: 'KIZARTMA' },
        { clueRow: 1, clueCol: 2, direction: 'down', clue: 'Kalınlığı veya kesiti az zayıf zarif olan', answer: 'İNCE' },
        { clueRow: 1, clueCol: 4, direction: 'down', clue: 'Gezegenlerin güneş çevresinde dolandığı yörünge düzlemi', answer: 'EKLİPTİK' },
        { clueRow: 8, clueCol: 8, direction: 'down', clue: 'Uzaklık veya abartma edatı', answer: 'TA' }
    ],
};

export const ch150: PuzzleSpec = {
    id: 'ch150',
    title: 'Efsane Canavar',
    rows: 11,
    cols: 11,
    theme: 'Genel',
    difficulty: 'hard',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Türkiye Cumhuriyeti\'nin kurucusu', answer: 'ATATÜRK' },
        { clueRow: 5, clueCol: 0, direction: 'across', clue: 'Futbolda ceza sahası içinde yapılan kusura karşılık atılan serbest atış', answer: 'PENALTI' },
        { clueRow: 9, clueCol: 2, direction: 'across', clue: 'Yazlık olan ter tutan pamuktan vs veya yakasız olan sportif kısa gömlek (T-Shirt ün okunuşu cinsi)', answer: 'TİŞÖRT' },
        { clueRow: 10, clueCol: 0, direction: 'across', clue: 'Kalan', answer: 'MÜTEBAKİ' },
        { clueRow: 1, clueCol: 2, direction: 'down', clue: 'Taze (yöresel)', answer: 'TEZE' },
        { clueRow: 1, clueCol: 4, direction: 'down', clue: 'Karşılık gelme (çekim)', answer: 'TEKABÜLİ' },
        { clueRow: 8, clueCol: 8, direction: 'down', clue: 'İşaret borusu sesi', answer: 'Tİ' }
    ],
};

export const ch151: PuzzleSpec = {
    id: 'ch151',
    title: 'Tanrılar Yolu',
    rows: 12,
    cols: 12,
    theme: 'Genel',
    difficulty: 'hard',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Ağırlığın az olması durumu, kolay taşınabilirlik', answer: 'HAFİFLİK' },
        { clueRow: 5, clueCol: 0, direction: 'across', clue: 'Bir ilimiz', answer: 'ERZİNCAN' },
        { clueRow: 10, clueCol: 2, direction: 'across', clue: 'Çok kısa bacaklı, özellikle eğlence lunapark vb yerlerde binilen tüylü küçük at', answer: 'MİDİLLİ' },
        { clueRow: 11, clueCol: 0, direction: 'across', clue: 'Radyo veya televizyon stüdyosunda haber okuyan, veya maç veya maç anlatan sunucu', answer: 'SPİKER' },
        { clueRow: 1, clueCol: 2, direction: 'down', clue: 'Büyükbaş veya küçükbaş at ve sığır beslenen koku yayan dışkı alanlı toprak tavan veya bina', answer: 'AHIR' },
        { clueRow: 1, clueCol: 4, direction: 'down', clue: 'Yok oluş (çekim)', answer: 'İZMİHLALİ' },
        { clueRow: 9, clueCol: 9, direction: 'down', clue: 'Bağlamaya yarayan lif', answer: 'İP' },
        { clueRow: 9, clueCol: 3, direction: 'down', clue: 'Bir nota; soru eki', answer: 'Mİ' }
    ],
};

export const ch152: PuzzleSpec = {
    id: 'ch152',
    title: 'Altın Işık',
    rows: 12,
    cols: 12,
    theme: 'Genel',
    difficulty: 'hard',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Amazon ormanlarında nehir yakınında bulunan devasa ebatlara varabilen dehşetengiz yılan', answer: 'ANAKONDA' },
        { clueRow: 5, clueCol: 0, direction: 'across', clue: 'Basamaklı yol', answer: 'MERDİVEN' },
        { clueRow: 10, clueCol: 2, direction: 'across', clue: 'Yıkıcı etkisi olan şiddetli rüzgar', answer: 'FIRTINA' },
        { clueRow: 11, clueCol: 0, direction: 'across', clue: 'Hainlik etme, güveni kötüye kullanma', answer: 'İHANET' },
        { clueRow: 1, clueCol: 2, direction: 'down', clue: 'Güzel kokulu, yaprakları çaya da katılan bir bitki', answer: 'NANE' },
        { clueRow: 1, clueCol: 4, direction: 'down', clue: 'Ayakkabı onaran veya yapan ayakkabıcı', answer: 'KUNDURACI' },
        { clueRow: 9, clueCol: 9, direction: 'down', clue: 'İsim', answer: 'AD' },
        { clueRow: 9, clueCol: 3, direction: 'down', clue: 'Bir nota', answer: 'FA' }
    ],
};

export const ch153: PuzzleSpec = {
    id: 'ch153',
    title: 'Olimpos Zirvesi',
    rows: 12,
    cols: 12,
    theme: 'Genel',
    difficulty: 'hard',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Sözleşme (çekim)', answer: 'TEKAVÜLİ' },
        { clueRow: 5, clueCol: 0, direction: 'across', clue: 'Konuşanın sesinin seviyesini hoparlöre veya kayda ileten baş aleti', answer: 'MİKROFON' },
        { clueRow: 10, clueCol: 2, direction: 'across', clue: 'Bilgi işlem', answer: 'BİLİŞİM' },
        { clueRow: 11, clueCol: 0, direction: 'across', clue: 'Yazıyı sese veya düşünceye çevirmek', answer: 'OKUMAK' },
        { clueRow: 1, clueCol: 2, direction: 'down', clue: 'Sıfırdan küçülen negatif değer bildiren işaret, dondurucu soğuk derecesi', answer: 'EKSİ' },
        { clueRow: 1, clueCol: 4, direction: 'down', clue: 'Gök cisimlerini inceleyen uzay bilimi', answer: 'ASTRONOMİ' },
        { clueRow: 9, clueCol: 9, direction: 'down', clue: 'Koyun sesi', answer: 'ME' },
        { clueRow: 9, clueCol: 3, direction: 'down', clue: 'İşaret sıfatı/zamiri', answer: 'BU' }
    ],
};

export const ch154: PuzzleSpec = {
    id: 'ch154',
    title: 'İlahi Güç',
    rows: 12,
    cols: 12,
    theme: 'Genel',
    difficulty: 'hard',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Uçamayan, koşucu başını kuma gömen dev kuş', answer: 'DEVEKUŞU' },
        { clueRow: 5, clueCol: 0, direction: 'across', clue: 'Haberleşme', answer: 'İLETİŞİM' },
        { clueRow: 10, clueCol: 2, direction: 'across', clue: 'Devletin temel yasası', answer: 'ANAYASA' },
        { clueRow: 11, clueCol: 0, direction: 'across', clue: 'Koltuktan büyük genelde 2.3 kişilik uzun, açılıp yatak da olabilen salon oturmalığı', answer: 'KANEPE' },
        { clueRow: 1, clueCol: 2, direction: 'down', clue: 'Güçlü istek, gaye', answer: 'EMEL' },
        { clueRow: 1, clueCol: 4, direction: 'down', clue: 'Müzik icra etmek, çalmak için kullanılan çalgının eş anlamlı ve akademik adı', answer: 'ENSTRÜMAN' },
        { clueRow: 9, clueCol: 9, direction: 'down', clue: 'Acı veya özlem ünlemi', answer: 'AH' },
        { clueRow: 9, clueCol: 3, direction: 'down', clue: 'Kısa zaman parçası, lahza', answer: 'AN' }
    ],
};

export const ch155: PuzzleSpec = {
    id: 'ch155',
    title: 'Tanrısal Zeka',
    rows: 12,
    cols: 12,
    theme: 'Genel',
    difficulty: 'hard',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Öç alma (çekim)', answer: 'İNTİKAMİ' },
        { clueRow: 5, clueCol: 0, direction: 'across', clue: 'Suyun veya çukurun dibe olan mesafesi', answer: 'DERİNLİK' },
        { clueRow: 10, clueCol: 2, direction: 'across', clue: 'Nohudun fırınlanıp çerez haline getirilmiş en bol bulunan kuruyemişi (sarı, beyaz cinsi var)', answer: 'LEBLEBİ' },
        { clueRow: 11, clueCol: 0, direction: 'across', clue: 'Bilinmeyen, giz', answer: 'MUAMMA' },
        { clueRow: 1, clueCol: 2, direction: 'down', clue: 'Sevinç, keyif, mutluluk', answer: 'NEŞE' },
        { clueRow: 1, clueCol: 4, direction: 'down', clue: 'İçinden inci çıkan kabuklu deniz canlısı', answer: 'İSTİRİDYE' },
        { clueRow: 9, clueCol: 9, direction: 'down', clue: 'Şehir, vilayet', answer: 'İL' },
        { clueRow: 9, clueCol: 3, direction: 'down', clue: 'Bir nota', answer: 'LA' }
    ],
};

export const ch156: PuzzleSpec = {
    id: 'ch156',
    title: 'Son Efsane',
    rows: 13,
    cols: 13,
    theme: 'Genel',
    difficulty: 'hard',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Ayağı korumak için giyilen giyecek', answer: 'AYAKKABI' },
        { clueRow: 5, clueCol: 0, direction: 'across', clue: 'Kararlılık, denge', answer: 'İSTİKRAR' },
        { clueRow: 10, clueCol: 2, direction: 'across', clue: 'Çekinmeden ileri atılan girişken gözüpek (7)', answer: 'ATILGAN' },
        { clueRow: 12, clueCol: 0, direction: 'across', clue: 'Üretim ve tüketim bilimi, iktisat', answer: 'EKONOMİ' },
        { clueRow: 1, clueCol: 2, direction: 'down', clue: 'Umutsuzluk, keder', answer: 'YEİS' },
        { clueRow: 1, clueCol: 4, direction: 'down', clue: 'Yetenek, yapabilme gücü', answer: 'KABİLİYET' },
        { clueRow: 9, clueCol: 9, direction: 'down', clue: 'Unutmamak için yazılan kısa yazı; okul değerlendirmesi', answer: 'NOT' },
        { clueRow: 9, clueCol: 3, direction: 'down', clue: 'Telefonda seslenme sözü', answer: 'ALO' }
    ],
};

export const ch157: PuzzleSpec = {
    id: 'ch157',
    title: 'Ölümsüz An',
    rows: 13,
    cols: 13,
    theme: 'Genel',
    difficulty: 'hard',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Her hafta', answer: 'HAFTALIK' },
        { clueRow: 5, clueCol: 0, direction: 'across', clue: 'Rulo halinde kıvrılan uzun bacaklarıyla çok sayıda (30-300) adımı bulunan yavaş haşeremsi', answer: 'KIRKAYAK' },
        { clueRow: 10, clueCol: 2, direction: 'across', clue: 'Nefsin isteklerini kırma, perhiz', answer: 'RİYAZET' },
        { clueRow: 12, clueCol: 0, direction: 'across', clue: 'Padişahların vs erkek çocullarına eski devirde verilen erkek veliaht adı (7)', answer: 'ŞEHZADE' },
        { clueRow: 1, clueCol: 2, direction: 'down', clue: 'Avlanan kimse', answer: 'AVCI' },
        { clueRow: 1, clueCol: 4, direction: 'down', clue: 'Türklük (çekim)', answer: 'TÜRKİYETİ' },
        { clueRow: 9, clueCol: 9, direction: 'down', clue: 'İnce, gözenekli kumaş', answer: 'TÜL' },
        { clueRow: 9, clueCol: 3, direction: 'down', clue: 'Can, tin', answer: 'RUH' }
    ],
};

export const ch158: PuzzleSpec = {
    id: 'ch158',
    title: 'Kaderin Sesi',
    rows: 13,
    cols: 13,
    theme: 'Genel',
    difficulty: 'hard',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Subaydan kıdemsiz rütbeli asker', answer: 'ASTSUBAY' },
        { clueRow: 5, clueCol: 0, direction: 'across', clue: 'Saygınlık', answer: 'HAYSİYET' },
        { clueRow: 10, clueCol: 2, direction: 'across', clue: 'Bkd as cd bd md fd d n ) ÖKSÜRÜK  (7 )', answer: 'ÖKSÜRÜK' },
        { clueRow: 12, clueCol: 0, direction: 'across', clue: 'Ağ ören çok bacaklı eklembacaklı', answer: 'ÖRÜMCEK' },
        { clueRow: 1, clueCol: 2, direction: 'down', clue: 'Asyadan kökenli, fasulyesi olup eti, sütü dahi sosu dahi taklit olarak ucuza yapılan sebze ürün', answer: 'SOYA' },
        { clueRow: 1, clueCol: 4, direction: 'down', clue: 'Ortamda hiçbir ses çıkmaması, sükunet hali', answer: 'SESSİZLİK' },
        { clueRow: 9, clueCol: 9, direction: 'down', clue: 'Birine karşı duyulan gizli ve bitmeyen düşmanlık', answer: 'KİN' },
        { clueRow: 9, clueCol: 3, direction: 'down', clue: 'Hayat belirtisi olmayan ve yaşamayan ceset donuk vb hal', answer: 'ÖLÜ' }
    ],
};

export const ch159: PuzzleSpec = {
    id: 'ch159',
    title: 'Sonsuzluk',
    rows: 13,
    cols: 13,
    theme: 'Genel',
    difficulty: 'hard',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Yemek ve salatalarda çokça kullanılan ot', answer: 'MAYDANOZ' },
        { clueRow: 5, clueCol: 0, direction: 'across', clue: 'Tren sürüsüne verilen isim', answer: 'MAKİNİST' },
        { clueRow: 10, clueCol: 2, direction: 'across', clue: 'Uzun omayan boy', answer: 'KISALIK' },
        { clueRow: 12, clueCol: 0, direction: 'across', clue: 'Simetri', answer: 'BAKIŞIM' },
        { clueRow: 1, clueCol: 2, direction: 'down', clue: 'Halka şeklinde pamuk gibi yumuşak ve yağlı mayalı hamur çöreği', answer: 'AÇMA' },
        { clueRow: 1, clueCol: 4, direction: 'down', clue: 'Suyun altında gidebilen savaş gemisi', answer: 'DENİZALTI' },
        { clueRow: 9, clueCol: 9, direction: 'down', clue: 'Apartman dairesi veya tabaka', answer: 'KAT' },
        { clueRow: 9, clueCol: 3, direction: 'down', clue: 'Bitkileri toprağa bağlayan bölüm', answer: 'KÖK' }
    ],
};

export const ch160: PuzzleSpec = {
    id: 'ch160',
    title: 'Büyük Zafer',
    rows: 13,
    cols: 13,
    theme: 'Genel',
    difficulty: 'hard',
    placements: [
        { clueRow: 2, clueCol: 0, direction: 'across', clue: 'Ruh bilimci', answer: 'PSİKOLOG' },
        { clueRow: 5, clueCol: 0, direction: 'across', clue: 'Yer seviyesine yakın veya düşük olma (şahsiyet vb) durumu', answer: 'ALÇAKLIK' },
        { clueRow: 10, clueCol: 2, direction: 'across', clue: 'Ekonomi', answer: 'İKTİSAT' },
        { clueRow: 12, clueCol: 0, direction: 'across', clue: 'Duymakla aynı anlamı veren sesin farkına varma algılama hissi eylemi (sağırın zıttı vs yapan vs.)', answer: 'İŞİTMEK' },
        { clueRow: 1, clueCol: 2, direction: 'down', clue: 'Giyim kuşamdaki usulün ve biçimin havanın yabancı kökenli ifade adı tarz', answer: 'STIL' },
        { clueRow: 1, clueCol: 4, direction: 'down', clue: 'Gündüzleri sofraya piknik veya mutfak artığına gelen büyük yapılı simsiyah baş belası kanatlı', answer: 'KARASİNEK' },
        { clueRow: 9, clueCol: 9, direction: 'down', clue: 'Kuşların vücudunu kaplayan örtü', answer: 'TÜY' },
        { clueRow: 9, clueCol: 3, direction: 'down', clue: 'Birden sonra gelen sayı', answer: 'İKİ' }
    ],
};

export const allUltraSpecs: PuzzleSpec[] = [
    ch121,
    ch122,
    ch123,
    ch124,
    ch125,
    ch126,
    ch127,
    ch128,
    ch129,
    ch130,
    ch131,
    ch132,
    ch133,
    ch134,
    ch135,
    ch136,
    ch137,
    ch138,
    ch139,
    ch140,
    ch141,
    ch142,
    ch143,
    ch144,
    ch145,
    ch146,
    ch147,
    ch148,
    ch149,
    ch150,
    ch151,
    ch152,
    ch153,
    ch154,
    ch155,
    ch156,
    ch157,
    ch158,
    ch159,
    ch160,
];

export const ultraChapterGroups = [
    { title: 'Yeni Keşif', subtitle: 'Yeni sırlar keşfet', puzzleIds: ['ch121', 'ch122', 'ch123', 'ch124', 'ch125'] },
    { title: 'Cesur Adım', subtitle: 'Atılgan ol', puzzleIds: ['ch126', 'ch127', 'ch128', 'ch129', 'ch130'] },
    { title: 'Derin Sular', subtitle: 'Derinlere in', puzzleIds: ['ch131', 'ch132', 'ch133', 'ch134', 'ch135'] },
    { title: 'Kaya Yüzü', subtitle: 'Sarp yollarda ilerle', puzzleIds: ['ch136', 'ch137', 'ch138', 'ch139', 'ch140'] },
    { title: 'Şimşek', subtitle: 'Hız ve güç', puzzleIds: ['ch141', 'ch142', 'ch143', 'ch144', 'ch145'] },
    { title: 'Ejderha', subtitle: 'Ejderhayı yen', puzzleIds: ['ch146', 'ch147', 'ch148', 'ch149', 'ch150'] },
    { title: 'Olimpos', subtitle: 'Tanrıların yolu', puzzleIds: ['ch151', 'ch152', 'ch153', 'ch154', 'ch155'] },
    { title: 'Efsanevi Son', subtitle: 'Efsaneyi yaz', puzzleIds: ['ch156', 'ch157', 'ch158', 'ch159', 'ch160'] },
];
