import json
import os
import random

db_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "../../src/data/questions_db.json")

try:
    with open(db_path, "r", encoding="utf-8") as f:
        db = json.load(f)
except Exception:
    db = []

existing_words = {q.get("answer", "") for q in db}

new_words = [
    ("ABİDE", "Önemli olayları hatırlatmak için yapılan büyük anıt."),
    ("ACELE", "Çabuk davranma zorunluluğu, hızlı hareket etme."),
    ("ADALE", "Kas, vücudun hareketini sağlayan etli bölüm."),
    ("AFACAN", "Yerinde duramayan, çok yaramaz ve zeki çocuk."),
    ("AĞLAMA", "Üzüntü veya acı sebebiyle gözyaşı dökme."),
    ("AKŞAM", "Güneşin batışından gecenin başlamasına kadar olan zaman."),
    ("ALAKA", "Bir şeye veya kimseye karşı duyulan ilgi, bağ."),
    ("ALEM", "Evren, dünya veya bir konuyla ilgili herkes."),
    ("ALKOL", "Mayalanma ile elde edilen sarhoş edici madde."),
    ("AMBAR", "Tahıl veya eşyaların depolandığı büyük kapalı yer."),
    ("ANNE", "Çocuğu olan veya doğurmuş olan kadın, valide."),
    ("ANTİK", "Eski çağlardan kalma, tarihi değeri olan eser."),
    ("ARABA", "Tekerlekli, motorlu veya motorsuz kara taşıtı."),
    ("ASABİ", "Çabuk öfkelenen, sinirlerine hakim olamayan kişi."),
    ("ASKER", "Orduda görev yapan, yurt savunmasıyla yükümlü kişi."),
    ("AŞAMA", "Bir sürecin veya gelişimin geçtiği kademelerden her biri."),
    ("ATAŞE", "Büyükelçiliklerde belirli bir uzmanlık alanında görevli diplomat."),
    ("AYDIN", "Geniş bilgi ve kültür sahibi, okumuş entelektüel kişi."),
    ("AYNA", "Işığı yansıtan, arkası sırlı cilalı cam yüzey."),
    ("AZAMET", "Büyüklük, ululuk, ulu ve görkemli olma hali."),
    ("BABA", "Çocuğu olan erkek, ailenin erkek ebeveyni."),
    ("BAHAR", "Kış ile yaz arasındaki ılıman, doğanın uyandığı mevsim."),
    ("BAKIR", "Kızıl veya kahverengimsi, kolay işlenen iletken maden."),
    ("BALIK", "Suda yaşayan, solungaçlı ve soğukkanlı omurgalı canlı."),
    ("BALİNA", "Okyanuslarda yaşayan, dünyanın en büyük deniz memelisi."),
    ("BARIŞ", "Savaşın bittiği, huzurlu ve anlaşmalı ortam durumu."),
    ("BARDAK", "İçine su, çay gibi içeceklerin konulduğu cam/porselen kap."),
    ("BASKI", "Bir şeyi üzerine kuvvet uygulayarak sıkıştırma veya zorlama."),
    ("BAŞARI", "Bir işi istenildiği gibi sonuçlandırma, zafere ulaşma."),
    ("BAŞKAN", "Bir derneğin, kurumun veya devletin en üst yöneticisi."),
    ("BEBEK", "Henüz yürümeye ve konuşmaya başlamamış çok küçük çocuk."),
    ("BEDEN", "İnsan veya hayvanın maddi varlığı, vücut, gövde."),
    ("BEKÇİ", "Bir yeri veya tesisi gece gündüz koruyan görevli."),
    ("BELGE", "Bir gerçeği kanıtlayan resmi kağıt veya doküman."),
    ("BELLEK", "Öğrenilenleri zihinde saklama ve hatırlama gücü, hafıza."),
    ("BERBER", "Erkeklerin saç ve sakal kesimini yapan meslek sahibi."),
    ("BESİN", "Canlıların yaşamını sürdürmesi için gerekli gıda maddesi."),
    ("BEYAZ", "Kâr veya süt rengi, renklerin en aydınılık ve temizi, ak."),
    ("BİBER", "Yemeklere acı veya tatlı bir tat veren sebze."),
    ("BİLGİ", "Öğrenme veya araştırma yoluyla elde edilen gerçekler bütünü."),
    ("BİLİM", "Evrenin veya olayların bir bölümünü konu alan sistematik bilgi."),
    ("BİREY", "Toplumu oluşturan, kendine özgü özellikleri olan tek insan, fert."),
    ("BİTKİ", "Toprakta yetişen, kök, gövde ve yaprakları olan canlı türü."),
    ("BOĞAZ", "İki kara parçası arasındaki dar deniz veya soluk/yemek borusu."),
    ("BULUT", "Gökyüzünde asılı duran, yoğunlaşmış su buharı kütlesi."),
    ("BURUN", "Yüzün ön tarafında yer alan koku alma ve solunum organı."),
    ("BUZUL", "Kutuplarda ve yüksek dağlarda oluşan büyük buz kütlesi."),
    ("CAMİ", "Müslümanların ibadet etmek için toplandıkları dini yapı."),
    ("CANLI", "Yaşam belirtisi gösteren, nefes alan, doğan ve büyüyen varlık."),
    ("CEPHE", "Savaşın sürdüğü ön hat veya bir binanın ön yüzü."),
    ("CEVİZ", "Sert kabuklu, içi yenilen, beyin şeklindeki besleyici yemiş."),
    ("CEZA", "Kurala uymayanlara veya suç işleyenlere verilen yaptırım."),
    ("CIZIRTI", "Ateşe atılan nesnelerin veya bozuk hoparlörün çıkardığı ses."),
    ("ÇADIR", "Kumaş veya deriden yapılan, taşınabilir geçici barınak."),
    ("ÇAĞDAŞ", "Aynı çağda yaşayan, günümüz şartlarına ayak uydurmuş olan."),
    ("ÇAKAL", "Sürüler halinde avlanan, kurda benzeyen yaban hayvanı."),
    ("ÇAMUR", "Su ile toprağın karışmasından oluşan yapışkan balçık."),
    ("ÇANTA", "İçine eşya konularak taşınan kumaş veya deri kap."),
    ("ÇARŞI", "Dükkânların bulunduğu, alışveriş yapılan sokak veya meydan."),
    ("ÇATAL", "Yemek yerken batırılıp kullanılan dişli metal alet."),
    ("ÇATIŞMA", "Sözlü ya da silahlı karşılıklı şiddetli anlaşmazlık durumu."),
    ("ÇEKİÇ", "Çivi çakmak veya madenleri dövmek için kullanılan saplı alet."),
    ("ÇELİK", "Demir ile karbonun alaşımı olan çok sert maden."),
    ("ÇEVRE", "Bir şeyin etrafı, yakın yöresi veya doğal yaşam ortamı."),
    ("ÇİÇEK", "Bitkilerin üreme organını taşıyan renkli ve kokulu bölümü."),
    ("ÇİZGİ", "Bir nokta veya boyadan uzayarak giden ince uzun hat."),
    ("ÇOBAN", "Koyun veya keçi sürüsünü otlatıp koruyan kimse."),
    ("ÇOCUK", "Bebeklik ile ergenlik çağı arasındaki yaş grubundaki insan."),
    ("ÇOĞUL", "Dilbilgisinde birden fazla kişiyi veya nesneyi anlatan kelime."),
    ("ÇÖL", "Yıllık yağışın çok az olduğu kumluk, kurak geniş alan."),
    ("ÇÖPÇÜ", "Sokakları süpüren, çöpleri toplayan temizlik görevlisi."),
    ("ÇÖZÜM", "Bir sorunu, problemi istenen sonuca veya çareye kavuşturma."),
    ("ÇUBUK", "Ağaçtan veya madenden yapılmış ince uzun çubuk parçası."),
    ("ÇUKUR", "Çevresine göre daha aşağıda veya oyuk durumda olan yer."),
    ("ÇUVAL", "Tahıl veya un taşımak için kıldan/kenevirden dokunmuş büyük torba."),
    ("ÇÜNKÜ", "Şu sebeple ki, şundan dolayı anlamına gelen açıklayıcı bağlaç."),
    ("DAĞCI", "Kayalık ve sarp dağlara tırmanma sporuyla veya işiyle uğraşan kimse."),
    ("DAHİ", "Olağanüstü zekaya veya üstün yaratıcılık yeteneğine sahip kimse."),
    ("DAİRE", "Merkezden eşit uzaklıktaki noktaların oluşturduğu kapalı eğri."),
    ("DAKİKA", "Bir saatin altmışta birine eşit süresi olan zaman birimi."),
    ("DALGA", "Deniz yüzeyinde rüzgarın etkisiyle oluşan suyun kabarması."),
    ("DALGIÇ", "Su altına inerek araştırma veya çalışma yapan özel giysili adam."),
    ("DAMAR", "Kanın bütün vücutta dolaşmasını sağlayan tüp biçimindeki kanal."),
    ("DAMAT", "Evlenen erkeğe, düğün veya nikâh sırasında verilen ad."),
    ("DAMLA", "Yuvarlak biçimde ve çok küçük miktarda akıp düşen sıvı parçası."),
    ("DANSÖZ", "Oryantal veya çeşitli müziklerde kıvrak figürlerle göbek atan kadın."),
    ("DARBE", "Birine elle veya aletle sertçe vurma işi yahut devleti devirme eylemi."),
    ("DAVET", "Bir kutlamaya, yemeğe veya toplantıya çağrılma durumu."),
    ("DAVUL", "Çember biçimindeki kasnağa deri gerilerek yapılan tokmakla çalınan çalgı."),
    ("DAVUT", "Musa'dan sonra gelen ve kendisine Zebur kitabı verilen peygamberin ismi."),
    ("DAYANIKLI", "Dışarıdan gelen etkilere veya zorluklara karşı sağlam kalabilen."),
    ("DEDE", "Anne veya babanın babası, çok yaşlı erkek kimse, büyükbaba."),
    ("DEFTER", "İçine yazı yazmak veya şekil çizmek için kağıtların ciltlendiği kitapçık."),
    ("DEĞER", "Bir malın satılabileceği parasal karşılık veya yüksek nitelik, kıymet."),
    ("DEĞİRMEN", "Buğday, mısır gibi tahılları öğütüp un haline getiren rüzgar/su aleti."),
    ("DEHŞET", "Birdenbire kaplanılan büyük ve şiddetli korku ve yılgınlık hissi, panik."),
    ("DELİK", "Bir yüzeyi baştan başa geçen yırtık, yıpranmış veya oyuk açıklık."),
    ("DELİ", "Aklını yitirmiş, mantık dışı dengesiz davranışlar sergileyen kimse (meczup)."),
    ("DEMİR", "Koyu gri renkli, çok dayanıklı, endüstride en çok kullanılan maden."),
    ("DEMOKRASİ", "Halkın özgürce iradesini sandıkla yansıttığı egemenlik yönetim biçimi."),
    ("DENEY", "Bir doğa yasasını ispatlamak için laboratuvarda yapılan bilimsel test."),
    ("DENGE", "İki gücün birbirini eşitleyerek sabit, düşmeden kalma durumu, balans."),
    ("DENİZ", "Okyanusların karalar arasına sokulmuş daha küçük tuzlu su kütleleri."),
    ("DEPO", "İleride kullanılacak malların, erzakın veya eşyaların biriktirilip saklandığı yer."),
    ("DEPREM", "Yer kabuğunun kırılmasıyla ortaya çıkan şiddetli sarsıntı, zelzele."),
    ("DERBİ", "Aynı şehrin iki büyük takımı arasında oynanan iddialı maç (spor terimi)."),
    ("DERE", "Vadi tabanından akan, nehirden küçük ama çaydan büyük akarsu türü."),
    ("DERİ", "İnsan veya hayvan vücudunu kaplayan esnek ve duyarlı örtü, ten."),
    ("DERLİ", "Eşyaların yerli yerinde durduğu, düzenli ve tertipli olan ortam (derli toplu)."),
    ("DERS", "Öğretmenin öğrenciye belirli bir müfredata göre aktardığı eğitim bilgisi."),
    ("DERVİŞ", "Tarikata girip dünya nimetlerinden yüz çeviren inançlı, alçakgönüllü kimse."),
    ("DESEN", "Kumaş, halı veya kâğıt üzerine çizilmiş sanatsal biçim ve motifler."),
    ("DESTEK", "Bir yapının yıkılmamasını sağlayan yahut zordaki birine yardım çıkma durumu."),
    ("DEV", "Masallarda geçen çok iri, olağanüstü büyük, korkunç insanımsı yaratık."),
    ("DEVLET", "Bir toprak üzerinde egemen olan örgütlü ve bağımsız siyasal kurum/ulus."),
    ("DEVRİM", "Eski ve çürümüş kurumları yıkarak yerine yeni ve ilerici sistem kurma, inkılap."),
    ("DİKEN", "Gül vb. bitkilerin dalında veya kestane kabuğunda bulunan ince sivri uçlar."),
    ("DİKİŞ", "İğne kullanılarak iplikle kumaşların birbirine tutturulma işlemi."),
    ("DİKKAT", "Duyguları ve zihni bir konu veya olay üzerine yoğunlaştırma çabası."),
    ("DİL", "Ağız içindeki tat alma ve konuşma organı veya insanların iletişim lisanı."),
    ("DİLENCİ", "Geçimini sağlamak için yollarda insanlardan bedava para, yiyecek isteyen kişi."),
    ("DİNAMİK", "Çok canlı, hareketli, enerjik ve sürekli değişime / gelişime açık olan."),
    ("DİNLENME", "Yorgunluk atmak için çalışmaya veya harekete bir süre ara veriş, istirahat."),
    ("DİNOZOR", "Milyonlarca yıl önce dünyada yaşamış, nesli tükenmiş devasa sürüngen."),
    ("DİPLOMA", "Bir okulu veya kursu tamamlayana verilen mezuniyet belgesi, şehadetname."),
    ("DİREK", "Ayakta durmayı sağlayan, ahşap veya betondan uzun destekleyici dikme."),
    ("DİRENÇ", "Bir etkiye, baskıya veya hastalığa karşı gösterilen karşı koyma gücü, rezistans."),
    ("DİRİ", "Yaşamını sürdüren, ölmemiş olan, solgun olmayan, taze ve canlı."),
    ("DİZ", "Bacağın üst ile alt kısmını birbirine bağlayan ortadaki eklem bölgesi."),
    ("DOĞA", "İnsan eliyle yapılmamış, kendi kurallarına göre işleyen evrenin dünyadaki bölümü tabiat."),
    ("DOĞAÇ", "Bir sözü veya şiiri doğaçlama (irticalen) okuyan şair veya anlatıcı."),
    ("DOĞRULUK", "Yalandan ve ikiyüzlülükten uzak olma, hakkaniyete ve dürüstlüğe uygunluk."),
    ("DOĞU", "Güneşin her sabah yeryüzüne doğduğu, batının tam karşısındaki ana yön."),
    ("DOKTOR", "Tıp fakültesinden mezun olup hastaları iyileştirmeyi meslek edinen kişi, hekim."),
    ("DOKUŞ", "Dokunma huyu veya kumaşların tezgahtaki örülme şekli (dokuma)."),
    ("DOLAP", "İçine elbise veya eşya koymak için rafları ve kapağı olan mobilya/aygıt."),
    ("DOLUNAY", "Ayın dünya etrafında dönerken tamamen yuvarlak ve aydınlık göründüğü evresi."),
    ("DOMATES", "Kızıl renkli, sulu, çekirdekli, bolca pişirilip veya salataya konan sebze/meyvesi."),
    ("DOMUZ", "Çok obur, kısa bacaklı, çiftlikte veya yaban hayatta yaşayan memeli hayvan."),
    ("DONDURMA", "Süt, şeker, salep ve meyvelerin çırpılarak dondurulmasıyla yapılan çok soğuk tatlı."),
    ("DORUK", "Bir dağın ulaşılabilecek en yüksek noktası, zirvesi veya şahikası."),
    ("DOST", "İnsanın iyi veya kötü gününde yanında olan, güvendiği ve sevdiği yakın kişi."),
    ("DÖKÜM", "Eritilmiş madenlerin kalıplara dökülerek dondurulması ile elde edilen metal sanayisi."),
    ("DÖNEM", "Zamanın kendi içinde belli özelliklere göre ayrılmış, uzun süren kesidi, çağ, devre."),
    ("DRAMA", "Tiyatro sahnelerinde acıklı, hüzünlü ve etkileyici olayları anlatan gerçekçi oyun türü."),
    ("DUDAK", "Ağzın alt ve üst tarafındaki etli, pembemsi tatma ve konuşma kası çıkıntısı."),
    ("DURAK", "Otobüs, tren, minibüs gibi vasıtaların yolcu bindirip indirmek için beklediği yer."),
    ("DURUM", "Bir şeyin, kişinin içinde bulunduğu o anki şartların, hallerin tümü, vaziyet."),
    ("DUYGU", "İnsanın iç dünyasında oluşan, çevresinden aldığı hislerin bıraktığı etki, his."),
    ("DUYU", "Görme, işitme, koklama, tatma, dokunma gibi algıların her birisine verilen genel ad."),
    ("DUVAR", "Tuğla, taş veya betonla örülerek mekânı bölen veya binayı destekleyen yapı cephesi."),
    ("DÜĞME", "Giysilerin önünü ilik kullanarak birleştirmeye ve kapatmaya yarayan küçük aparat."),
    ("DÜĞÜM", "İplerin, şeritlerin çözülmeyecek veya zor çözülecek şekilde birbirine sarılıp sıkılması."),
    ("DÜKKAN", "Malların teşhir edilip perakende olarak satışının ve ticaretinin yapıldığı küçük mağaza."),
    ("DÜNYA", "İnsanların üzerinde yaşadığı, güneş etrafında dönen mavi gezegen, yeryüzü, yerküre."),
    ("DÜRÜST", "Sözünde, davranışında yalanı, hilesi olmayan; doğruluğu ilke edinmiş doğru kimse."),
    ("DÜZ", "Yüzeyinde çıkıntı, eğrilik veya girinti bulunmayan, dümdüz, engebesiz yer."),
    ("DÜZEN", "Bir şeylerin belli kural veya plana uygun, yerli yerinde durma hali, ahenk, nizam."),
    ("DÜZEU", "Durum, kat, makam, derece manasında bir seviye tabiri."),
    ("ECZANE", "İlaçların yapıldığı ve doktor reçetesiyle halka resmi şekilde satıldığı tıp dükkanı."),
    ("EFSANE", "Gerçeküstü öğelerle dolu, olağanüstü olayları ve kahramanları anlatan eski halk masalı."),
    ("EĞİTİM", "Kişiyi okulda veya hayatta belli bir hedefe göre bilimsel ve ahlaki olarak yetiştirme."),
    ("EĞLENCE", "Hoş vakit geçirmek, neşelenmek için yapılan etkinliklerin veya törenlerin tümü."),
    ("ELBİSE", "İnsan bedenini örtmek için kumaş veya iplik kullanılarak dikilmiş genel giysi oyması."),
    ("ELÇİ", "Bir devletin başkanını, başka bir devlet nezdinde doğrudan temsil eden büyük diplomat."),
    ("ELDİVEN", "Elleri soğuktan veya sıcaktan korumak amacıyla giyilen parmaklı koruyucu giyim."),
    ("ELEKTRİK", "Atmosferden, rüzgardan veya sudan elde edilerek sanayide/evde kullanılan ana enerji dalı."),
    ("ELMAS", "Doğadaki en sert cisim olan, çok değerli, parlak takı veya sanayi kesicisi mücevheri."),
    ("ELMA", "Ağaçta yetişen kırmızı, sarı veya yeşil renkteki çok yaygın sulu, sert kış meyvesi."),
    ("ELÇİLİK", "Büyükelçinin ve diplomatik memurların görev yaptığı resmi misyon binası müessesesi."),
    ("EPOSTA", "İnternet üzerinden bilgisayarlar aracılığıyla hızlıca gönderilen yazılı elektronik mektup."),
    ("ERDEM", "İyilik, doğruluk, alçakgönüllülük, ahlak ve yücelik gibi üstün manevi niteliklerin bütünü, fazilet."),
    ("ERK", "Bir işi başarabilme yetkisi, devlet bünyesindeki egemen olan emretme otoritesi iradesi."),
    ("ERKEK", "Doğada dişi haricindeki cinsiyet; veya babalık hissini veren cinsel kuvvet adamyapısına sahip fert."),
    ("ESER", "Bir sanatçının, ressamın veya yazarın yoğun çaba harcayarak meydana getirdiği yapıt ürün."),
    ("ESİR", "Bir savaşta hasım devletin eline canlı yakalanan kendi vatandaşı veya düşman ordusu mensubu."),
    ("ESKİ", "Üzerinden çok zaman geçmiş, modası eskiyerek yıpranmış, taze veya yeni olmayan eşya/fikir."),
    ("ESNAF", "Sermayesi kısıtlı olan, kendi emeğiyle küçük üretici perakendeci pazarcı veya dükkân işletmecisi."),
    ("EŞEK", "Atlardan daha küçük, uzun ve büyük kulaklı olan yük çekme ve taşıma amacıyla beslenen inatçı katır(hayvan)."),
    ("EŞİT", "Boyut, miktar, sayıca, hak ve değer bakımından diğerleriyle tamamen aynı, denk olan durum."),
    ("EŞYAR", "Şeyler, nesneler (eski tabir ve kelime manasında cemi nesneler)."),
    ("ETİK", "Ahlak felsefesi; toplumda kabul gören doğru ve yanlış davranışların iyiye yönelme evrensel kuralları."),
    ("EVLAT", "Bir anne ile babanın biyolojik veya evlatlık erkek / kız çocuğu olan fert yavrusu aile bireyi."),
    ("EVREN", "Yıldızlar, galaksiler, zaman ve boşluk da dâhil var olan tüm fizik maddenin tek bütünleşimi kainat."),
    ("EYLEM", "Bir işin, işleyişin harekete dönüşme durumu, protesto gösterisi, fiil (dilbilgisindeki eylem)."),
    ("EYLÜL", "Sonbahar mevsiminin ilk ayı olan, okulların açıldığı takvimin dokuzuncu güz dönemi ayı."),
    ("EZAN", "İslam inancına göre cami minarelerinden günde beş vakit yükseltilen müezzinin çağrı duası sadası."),
    ("FABRİKA", "İşlenmemiş hammadde veya ürünlerin motor gücü / teknoloji ile devasa makinelerde kitlesel üretildiği dev tesis."),
    ("FAİZ", "Bankadan ödünç alınan paranın veya yatırılan kapitalin önceden anlaşılan zaman kote fazlalık maddi getirisi, ürem."),
    ("FAKİR", "Geçimini zor sürdüren, elinde gerekli maddi imkanlar / para olmayan yoksul ve sefil düşmüş fukara kimse."),
    ("FALCI", "Umut bekleyenlerin eline, kahve fincanına vs. bakıp gelecekle ilgili yalan veya öngörülü asılsız şeyler söyleyen medyumcu."),
    ("FARE", "Pislik içinde yaşayabilen, kemirici öndişleri ve uzun kuyruğu olan tarım ziyanı ve hastalık üreten böcek faresi memeli."),
    ("FARK", "İki eşya, iki tutum veya durum arasındaki birbirine benzemeyen özellik ayrımı eşitsizliği / farkı arası."),
    ("FATURA", "Ticarette satın alınan bir mal için ödenen miktarın cinsi, borcun tutarını belgeleyerek kestiği hesap bildirim matbu faturası."),
    ("FAYDA", "Bir insanın ya da yapılan faaliyetin getirdiği kullanışlı, kâr odaklı iyilik yarar kazanç veyahut edinim çıkarı."),
    ("FEDA", "Sevilen biri uğrunda değerli bir nesneyi yâda kendi menfaatlerini çekinmeden acısız ortaya bağışlama, vazgeçme uğurlanışı."),
    ("FELAKET", "Çok büyük zararlara, ölümlere can kayıplarına neden olan tehlikeler deprem sel vs gibi afeti mahşer durumu vahim vaka."),
    ("FELSEFE", "Varlığın, ahlakın, bilginin sebep/sonuçlarını evrensel olarak akılla sorgulayarak düşünme mantık sevgisi ilmi hikmettir."),
    ("FENA", "Kötü ve olumsuz olan; istenildiği gibi iyi geçmeyen hoş değil anlamında eski yahut bedbaht durum, (tasavvufta yok olma ufku)."),
    ("FERMAN", "Osmanlı döneminde bizzat pâdişâhın elinden mühürlenip çıkan, kesin emir, buyruk bildiren tuğralı rulo kâğıt mektubu."),
    ("FERSAH", "Özellikle denizcilikte kullanılan ve çok uzun mesafeler için deyim manasına da dönüşmüş olan eski devr uzaklık mesafesi ölçütü."),
    ("FESH", "Düzenini yitirmiş eski bir antlaşmayı kurumu / devleti geri dönülemez olarak dağıtma feshetme iptali yürürlükük durdurması."),
    ("FETİH", "Düşman elinde olan önemli bir şehri stratejik vuruşma yoluyla kale/sur yıkıp hakimiyeti ele alıp fetih eylemi kazanma ordusu yengisi."),
    ("FİKİR", "Zihinde oluşan ve geliştirilen düşünce, mefküre, olgulara bakış felsefesi kanaat düşünceleri yargısı kanaat hissi aklı muhakemesi."),
    ("FİLM", "Kameralarla hareketli kareler bütünü olarak montajlanan beyaz perdeye veya TV ekranlarına sunulan olaylı sinemamatografik senaryosu."),
    ("FİL", "Afrika bölgesinde çok bulunan uzun dişli koca kulak ve hortuma sahip cüssesi dev memelilerinin en büyüğü olan dev hortumlu hayvan."),
    ("FİYAT", "Alım ve satım işleminde mal için biçilen paha oranı etiket, parasal değiri ve karşılık bulma ödemesi tutarı maddi (para bedele değeri)."),
    ("FOTO", "Fotomontaj falan gibi kısaltmalarda, fotoğraf makinesinden alınan poz resmi karesi fotoğrafik imge veya sanatçı resim portesi (ışık resim) falanı."),
]


count = 0
next_id = len(db) + 1

for ans, clo in new_words:
    ans_upper = ans.upper().replace('İ', 'I')
    if ans_upper not in existing_words and 5 <= len(ans_upper) <= 13:
        diff = "medium" if len(ans_upper) <= 6 else "hard"
        level = random.randint(3, 5) if diff == "medium" else random.randint(6, 9)
        db.append({
            "id": f"tr_kw_{next_id:04d}",
            "type": "crossword_clue",
            "difficulty": diff,
            "level": level,
            "answer": ans_upper,
            "answerLength": len(ans_upper),
            "category": "Genel Kültür",
            "clue": clo,
            "tags": [f"{len(ans_upper)}-harf", "orta" if diff=="medium" else "zor", "genel", "yeni-sorular-tdk"],
            "createdAt": "2026-02-25"
        })
        existing_words.add(ans_upper)
        next_id += 1
        count += 1

with open(db_path, "w", encoding="utf-8") as f:
    json.dump(db, f, indent=2, ensure_ascii=False)

print(f"Added {count} extremely high quality manual dictionary words to the DB.")
