import json
import os
import random

db_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "../../src/data/questions_db.json")

try:
    with open(db_path, "r", encoding="utf-8") as f:
        db = json.load(f)
except Exception:
    db = []

existing_words = {q.get("answer", "") for q in db}

new_words = [
    ("ABAKÜS", "Sayı boncuğu, hesap aracı."),
    ("ABANOZ", "Çok sert ve ağır, siyah renkli bir ağaç."),
    ("ABARTI", "Bir şeyi olduğundan daha büyük veya çok gösterme."),
    ("ABİS", "Okyanusların en derin karanlık yeri."),
    ("ABLUKA", "Bir yeri dış dünya ile iletişimden kesme."),
    ("ABONE", "Süreli yayınları parasını ödeyerek alan kimse."),
    ("ACAR", "Güçlü, becerikli ve atılgan kişi."),
    ("ACAYİP", "Alışılmışın dışında olan, tuhaf."),
    ("ACELE", "Çabuk davranma zorunluluğu, ivedi."),
    ("ACENTE", "Bir kuruluşun işlerini yürüten ticari temsilcilik."),
    ("ACIMASIZ", "Merhameti olmayan, taş yürekli."),
    ("AÇGÖZLÜ", "Aza kanaat etmeyen, doymazlık."),
    ("AÇIKGÖZ", "Uyanık ve çıkarlarını iyi bilen."),
    ("ADALET", "Hak ve hukuka uygunluk, doğruluk."),
    ("ADAY", "Bir görev veya iş için kendini ileri süren kimse."),
    ("ADİSYON", "Lokantalarda hesabı gösteren kâğıt."),
    ("AFAKAN", "Sıkıntı veya heyecanla gelen hafakan, çarpıntı."),
    ("AFACAN", "Ele avuca sığmayan, akıllı ve yaramaz çocuk."),
    ("AFFETMEK", "Bir suçu bağışlamak, cezadan vazgeçmek."),
    ("AFİŞ", "Duvarlara asılan büyük boy ilan."),
    ("AĞBEY", "Büyük erkek kardeş."),
    ("AĞDAŞ", "Aynı ağdan veya sistemden olan."),
    ("AĞIRLIK", "Bir cismin yerçekimi altındaki kütlesi."),
    ("AHENK", "Uyum, düzen, seslerin veya renklerin uyumu."),
    ("AHLAK", "Kişinin doğuştan veya sonradan edindiği tutum ve davranışların tümü."),
    ("AHMAK", "Aklı az, bön, zekâsı gelişmemiş."),
    ("AHTAPOT", "Sekiz kollu, denizlerde yaşayan yumuşakça."),
    ("AİDİYET", "Bir yere, gruba veya kişiye ait olma hissi."),
    ("AKADEMİ", "Bilgin, yazar ve sanatçıların oluşturduğu kurul."),
    ("AKARSU", "Yeryüzünde veya yeraltında akan su kütlesi."),
    ("AKCİĞER", "Solunumu sağlayan temel organ."),
    ("AKILLI", "Aklını iyi kullanan, düşünceli, zeki."),
    ("AKŞAM", "Günün bitip güneşin battığı zaman."),
    ("AKTAR", "Baharat, şifalı otlar vb. satan dükkân veya kişi."),
    ("AKUSTİK", "Ses bilimi veya ses yankılanma düzeni."),
    ("AKYUVAR", "Kanda savunma yapan beyaz hücreler."),
    ("ALACALI", "Üzerinde çeşitli renkler veya lekeler bulunan."),
    ("ALARM", "Bir tehlikeyi veya uyarıyı bildiren işaret."),
    ("ALBAY", "Yarbay ile Tuğgeneral arasındaki askeri rütbe."),
    ("ALDATMA", "Bir kimseyi kandırmak veya ihanet etmek."),
    ("ALERJİ", "Vücudun bazı maddelere gösterdiği aşırı tepki."),
    ("ALINTI", "Bir yazıdan, eserden alınan parça, iktibas."),
    ("ALIŞKANLIK", "Sık tekrarlanarak huy haline gelmiş davranış."),
    ("ALKIŞ", "Beğeni ve takdir için el çırpma eylemi."),
    ("ALYANS", "Nişan veya evlilik yüzüğü."),
    ("AMATÖR", "Bir işi meslek olarak değil hobi olarak yapan."),
    ("AMBALAJ", "Eşyaların taşınması için kullanılan sarma malzemesi."),
    ("AMBAR", "Tahılların veya malzemelerin saklandığı büyük depo."),
    ("AMBULANS", "Hastaları hastaneye taşıyan özel donanımlı araç."),
    ("AMELİYAT", "Cerrahların hastayı keserek yaptığı tedavi işlemi."),
    ("AMİGO", "Spor karşılaşmalarında taraftarları coşturan kişi."),
    ("AMORTİ", "Piyangoda bilet bedelinin geri ödenmesi."),
    ("ANADOLU", "Asya kıtasının batıya uzanan yarımadası, Türkiye toprakları."),
    ("ANAHTAR", "Kilitleri açıp kapamaya yarayan metal alet."),
    ("ANANAS", "Üzeri pullu, iri gövdeli, tatlı sarmal meyve."),
    ("ANANEVİ", "Geleneksel, atadan kalma olan."),
    ("ANARŞİ", "Başıbozukluk, devlet otoritesinin yokluğu."),
    ("ANAYASA", "Devletin temel kurumlarını düzenleyen en üst yasa."),
    ("ANDROİD", "İnsana benzeyen veya andıran robot."),
    ("ANEMON", "Dağ lalesi olarak da bilinen çok tüyülü bitki."),
    ("ANGARYA", "Zorla ve ücretsiz olarak yaptırılan iş."),
    ("ANITKABİR", "Mustafa Kemal Atatürk'ün Ankara'daki anıt mezarı."),
    ("ANKARA", "Türkiye Cumhuriyeti'nin başkenti."),
    ("ANONİM", "Yazarı, yapanı veya söyleyeni bilinmeyen."),
    ("ANORMAL", "Normal olmayan, olağanın dışındaki."),
    ("ANTEN", "Elektromanyetik dalgaları alan veya yayan tel."),
    ("ANTİKA", "Eski çağlardan kalma değerli, nadir eser."),
    ("ANTRENMAN", "Sporcuların yarışmalara hazırlanma çalışması, idman."),
    ("ANTRENÖR", "Sporcuları eğiten, çalıştıran kimse."),
    ("APARTHOTEL", "Daire şeklinde kiralanabilen otel."),
    ("APARTMAN", "Birçok ailenin oturduğu çok katlı yapı."),
    ("APSTRE", "Soyut, anlaşılması güç sanat dalı."),
    ("ARABESK", "Girişik bezeme biçimi veya bir müzik türü."),
    ("ARABULUCU", "Karşıt görüşlü iki tarafı uzlaştıran kişi."),
    ("ARAÇ", "Bir işi yapmak için kullanılan eşya veya taşıt."),
    ("ARAKİYE", "Mevlevilerin giydiği ince keçe külah."),
    ("ARASTA", "Çarşılarda aynı esnafın bulunduğu bölüm."),
    ("ARAŞTIRMA", "Bir gerçeği ortaya çıkarmak için yapılan inceleme."),
    ("ARAZİ", "Büyük toprak parçası, yeryüzü parçası."),
    ("ARDIŞIK", "Birbiri ardına gelen, peş peşe olan."),
    ("ARGÜMAN", "Bir iddiayı destekleyen kanıt veya tez."),
    ("ARIZA", "Makinelerde veya sistemlerde meydana gelen bozukluk."),
    ("ARKEOLOJİ", "Geçmiş uygarlıklara ait kalıntıları inceleyen bilim, kazıbilim."),
    ("ARMADA", "Otluk veya donanma (büyük savaş filosu)."),
    ("ARMAĞAN", "Birini sevindirmek için verilen şey, hediye."),
    ("ARMONİ", "Müzikte seslerin üst üste uyumlu birlikteliği."),
    ("ARSENİK", "Çok zehirli kimyasal bir element."),
    ("ARSLAN", "Ormanlar kralı olarak bilinen yırtıcı büyük kedi hayvan."),
    ("ARŞİV", "Resmi veya edebi belgelerin saklandığı yer, belgelik."),
    ("ASABİYET", "Sinirlilik, çabuk öfkelenme durumu."),
    ("ASALAK", "Başkasının sırtından geçinen veya yaşayabilen canlı."),
    ("ASANSÖR", "Binalarda katlar arası inmeyi çıkmayı sağlayan kabin."),
    ("ASAYİŞ", "Bir yerdeki düzen, güvenlik ve huzur durumu."),
    ("ASGari", "En az, en alt olan derece."),
    ("ASİL", "Soylu, yüce duygularla hareket eden kimse."),
    ("ASİMETRİK", "Bakışımlı olmayan, iki yanı birbirine uymayan."),
    ("ASIR", "Yüzyıllık zaman dilimi, yüzyıl."),
    ("ASKILI", "Omuzdan askısı olan (giysi veya çanta)."),
    ("ASUMAN", "Gökyüzü, gök."),
    ("AŞAMA", "Bir işin gelişmesindeki her bir evre, kademe."),
    ("AŞAĞI", "Alt taraf, yüksek olmayan yer."),
    ("AŞÇI", "Mesleği yemek pişirmek olan kimse."),
    ("AŞİKÂR", "Açık, belli, herkesin görebileceği şekilde."),
    ("ATAK", "Üzerine düşeni yapmaktan çekinmeyen, girişilken veya hücum."),
    ("ATALET", "Tembellik, eylemsizlik."),
    ("ATASÖZÜ", "Geçmişten gelen, öğüt veren kalıplaşmış söz."),
    ("ATILIM", "İleriye doğru atılma, hamle, yenilik içeren ilerleme."),
    ("ATMACA", "Yırtıcı, küçük, esnek kanatlı bir avcı kuş."),
    ("ATMOSFER", "Dünyayı çepeçevre saran gaz tabakası, havayuvarı."),
    ("ATOM", "Kimyasal elementlerin en küçük yapı taşı."),
    ("AVANTAJ", "Üstünlük sağlayan durum, yarar."),
    ("AVES", "Aylak, serseri, işsiz güçsüz dolaşan (halk ağzı)."),
    ("AVUKAT", "Hak arayanları mahkemelerde savunan hukukçu."),
    ("AYAKKABI", "Ayağı korumak için giyilen eşya."),
    ("AYDINLIK", "Işık alan, karanlık olmayan yer."),
    ("AYNI", "Başkalığı, farkı olmayan, tıpkısı."),
    ("AYRICALIK", "Başkalarından ayrı, üstün tutulma durumu, imtiyaz."),
    ("AZADEL", "Kuruntu, vesvese (eski dil)."),
    ("AZAMET", "Büyüklük, ululuk, ulu ve görkemli olma hali."),
    ("AZİZ", "Ermiş kimse veya saygıdeğer olan."),
    ("BADEMCİK", "Boğazın iki yanında bulunan badem biçimli bezeler."),
    ("BAĞIMSIZ", "Hiçbir şeye veya kimseye bağlı olmayan, hür."),
    ("BAĞIŞIKLIK", "Vücudun mikroplara karşı gösterdiği savunma ve direnç."),
    ("BAHANE", "Bir hatayı veya gidememeyi gizlemek için gösterilen uydurma sebep."),
    ("BAHARAT", "Yemeklere lezzet katmak için kullanılan kök vb. şeyler (karabiber, tarçın)."),
    ("BAHÇIVAN", "Geçimini bahçe işlerinden, bitki bakımından sağlayan kimse."),
    ("BAHİS", "İki kişi arasında sonucu bilinmeyen bir şeye para yatırma, iddia."),
    ("BAKIR", "Kırmızımsı renkli, ısıyı ve elektriği iyi ileten maden."),
    ("BAKLAVA", "İnce yufkaların arasına fıstık vb. konularak yapılan şerbetli tatlı."),
    ("BAKTERİ", "Tek hücreli organizma, mikrop."),
    ("BALİNA", "Okyanuslarda yaşayan en büyük deniz memelisi hayvan."),
    ("BALKON", "Binaların dış yüzeyine doğru çıkıntılı olan bölümü."),
    ("BALSAM", "Bazı ağaçlardan elde edilen kokulu reçine, pelesenk."),
    ("BALTA", "Ağaç kesmek veya parçalamak için kullanılan çelik alet."),
    ("BANDAJ", "Yarayı sarmak veya korumak için kullanılan sargı bezi."),
    ("BANKNOT", "Kâğıt para."),
    ("BANYO", "İçinde yıkanılan oda."),
    ("BARAKA", "Tahtadan yapılmış geçici serme yapı."),
    ("BARIŞ", "Savaşın bittiği ve antlaşmanın sağlandığı durum, sulh."),
    ("BARO", "Bir şehirdeki avukatların kayıtlı olduğu meslek kuruluşu."),
    ("BAROMETRE", "Açık hava basıncını ölçen alet."),
    ("BARUT", "Ateşli silahlarda itici güç olarak kullanılan patlayıcı madde."),
    ("BARYUM", "Gümüş beyazı renginde bir element (Ba)."),
    ("BASINÇ", "Bir yüzeye dışarıdan uygulanan dik kuvvet, tazyik."),
    ("BASKI", "Zorlama, kısıtlama veya matbaada kitap basma işi."),
    ("BASKÜL", "Ağır yükleri tartmaya yarayan büyük alet."),
    ("BAŞARI", "Bir işin üstesinden gelebilme, iyi bir sonuca ulaşma."),
    ("BAŞKAN", "Bir derneğin, devletin veya kuruluşun baş yöneticisi."),
    ("BAŞKENT", "Devletin yönetim merkezi olan en önemli şehir."),
    ("BAŞLIK", "Bir yazının başına konan ve konuyu belirten kısa söz."),
    ("BATAKLIK", "İçine girildiğinde batılan, çamur ve suların biriktiği alan."),
    ("BATARYA", "Pil grubu veya savaş toplarından oluşan takım."),
    ("BATI", "Güneşin battığı yön, garp."),
    ("BAYKUŞ", "Geceleri avlanan, öttüğünde uğursuzluk getirdiğine inanılan kuş."),
    ("BAYRAK", "Bir ulusun bağımsızlık sembolü olan bez."),
    ("BAYT", "Bilgisayarlarda 8 bitten oluşan veri birimi."),
    ("BEDAVA", "Para ödenmeyen, karşılıksız olan, ücretsiz."),
    ("BEDEL", "Bir şeyin değeri, karşılığı veya uğruna verilen şey."),
    ("BEDEN", "İnsanın canlı yapısı, vücut, gövde."),
    ("BEKÇİ", "Bir yeri bekleyen, korumakla görevli kişi."),
    ("BELA", "İçinden çıkılması zor durum, sıkıntı, musibet."),
    ("BELGE", "Bir gerçeği ispat etmeye yarayan kâğıt türü, vesika."),
    ("BELLEK", "Yaşananları ve öğrenilenleri akılda tutma gücü, hafıza."),
    ("BENZİN", "Otomobillerde kullanılan petrol türevi yakıt."),
    ("BERABER", "Bir arada, birlikte."),
    ("BERBER", "Erkeklerin saç ve sakalını kesen, tıraş eden esnaf."),
    ("BERRAK", "Duru, temiz, bulanık olmayan."),
    ("BESİN", "Yaşamak ve büyümek için yenilen her şey, gıda."),
    ("BEŞİK", "Bebekleri uyutmak için sallanabilen küçük yatak."),
    ("BETON", "Çimento, kum, su ve taşlardan yapılan sert inşaat malzemesi."),
    ("BEYAN", "Söyleme, bildirme, açıkça ortaya koyma, duyuru."),
    ("BEYAZ", "En açık renk, kar rengi, ak."),
    ("BEYİN", "Kafatasının içinde yer alan merkezi sinir sistemi organı."),
    ("BEZELYE", "Küçük yeşil taneleri olan, yemeklerde kullanılan bitki."),
    ("BIÇAK", "Ekmek, et, vb. kesmeye yarayan saplı ve keskin alet."),
    ("BIGUDI", "Kadınların saçlarına bukle yapmak için sardıkları küçük alet."),
    ("BIYIK", "Üst dudak ile burun arasında çıkan kıllar."),
    ("BİBER", "Yemeklere acı veya tatlı lezzet vermek için konulan sebze/baharat."),
    ("BİBERON", "Bebeklere süt vb. içirmek için kullanılan lastik emzikli şişe."),
    ("BİBLİYOĞRAFYA", "Özel bir konu ile ilgili kitapların listesi, kaynakça."),
    ("BİÇİM", "Bir nesnenin dış görünüşü, şekli, görünümü."),
    ("BİLANÇO", "Bir işletmenin kâr ve zararla mali durumunu gösteren tablo.")
]

count = 0
next_id = len(db) + 1

for ans, clo in new_words:
    ans_upper = ans.upper().replace('İ', 'I')
    if ans_upper not in existing_words and 5 <= len(ans_upper) <= 13:
        diff = "medium" if len(ans_upper) <= 6 else "hard"
        level = random.randint(3, 5) if diff == "medium" else random.randint(6, 9)
        db.append({
            "id": f"tr_kw_{next_id:04d}",
            "type": "crossword_clue",
            "difficulty": diff,
            "level": level,
            "answer": ans_upper,
            "answerLength": len(ans_upper),
            "category": "Genel Kültür",
            "clue": clo,
            "tags": [f"{len(ans_upper)}-harf", "orta" if diff=="medium" else "zor", "genel", "yeni-sorular-tdk"],
            "createdAt": "2026-02-25"
        })
        existing_words.add(ans_upper)
        next_id += 1
        count += 1

with open(db_path, "w", encoding="utf-8") as f:
    json.dump(db, f, indent=2, ensure_ascii=False)

print(f"Added {count} extremely high quality manual dictionary words to the DB.")
