import json
import os
import random

db_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "../../src/data/questions_db.json")

try:
    with open(db_path, "r", encoding="utf-8") as f:
        db = json.load(f)
except Exception:
    db = []

existing_words = {q.get("answer", "") for q in db}

new_words = [
    ("CADDE", "Şehir içindeki ana yollara verilen isim."),
    ("CAHİL", "Okuyup yazması olmayan, bilgisiz kişi."),
    ("CAMBAZ", "İpte yürüyen ve tehlikeli gösteriler yapan kimse."),
    ("CAMEKAN", "Dükkanların camla örtülü vitrin bölümü."),
    ("CANAVAR", "Korkunç ve yırtıcı masal yaratığı."),
    ("CANDAN", "İçten, yürekten, samimi."),
    ("CAVİDAN", "Sonsuz, ölümsüz, ebedi (eski dilde)."),
    ("CAZGIR", "Güreşlerde pehlivanları tanıtan kişi veya şirret kimse."),
    ("CEBECİ", "Osmanlı'da silah tamiri yapan asker sınıfı."),
    ("CEBİR", "Kaba kuvvet, zorlama veya harfli matematik dalı."),
    ("CEFAKAR", "Çile çeken, üzüntü veya eziyetle yaşayan."),
    ("CEHALET", "Bilgisizlik, eğitim eksikliği."),
    ("CELALLİ", "Çabuk sinirlenen, öfkeli."),
    ("CELLAAT", "Ölüm cezasını infaz eden görevli."),
    ("CEMAAT", "Birlikte ibadet eden topluluk."),
    ("CEMİYET", "İnsan topluluğu veya dernek."),
    ("CEMRE", "Bahar başlarında havaya, suya ve toprağa düştüğü sanılan ısı."),
    ("CENARE", "Cenaze kelimesinin eski söylenişi, ölü."),
    ("CENGAVER", "Savaşa yatkın, savaşçı ruhlu yiğit."),
    ("CENNET", "İnançlara göre iyilerin gideceği ahiret yurdu."),
    ("CEPHE", "Savaşın sürdüğü ön saf, yüz, yüzey."),
    ("CERAHAT", "Yarada toplanan irin."),
    ("CESARET", "Korku karşısındaki dayanma ve ataklık gücü, yüreklilik."),
    ("CEST", "Duyguyu anlatmak için yapılan el ve kol hareketi."),
    ("CEVABEN", "Yanıt olarak, cevaben yazılan."),
    ("CEVAHİR", "Değerli taşlar, elmas, zümrüt vb. mücevherler."),
    ("CEVHER", "Bir şeyin özü veya işlenmemiş değerli maden."),
    ("CEVVAL", "Çabuk davranan, hareketli, enerjik."),
    ("CEZİRE", "Dört tarafı suyla çevrili kara parçası, ada."),
    ("CILIZ", "Çelimsiz, zayıf yapılı, güçsüz."),
    ("CIMBIZ", "Kıl veya ufak parça tutmaya yarayan küçük maşa."),
    ("CİDDİYET", "Ağırbaşlılık, şaka olmama durumu."),
    ("CİHAZ", "Bir işi yapmak için düzeneği olan alet."),
    ("CİLVESİZ", "Nazlanmayan, olduğu gibi davranan."),
    ("CİMRİ", "Parasından harcamaya kıyamayan, hasis."),
    ("CİNAYET", "İnsan öldürme eylemi veya ağır suç."),
    ("CİNSİYET", "Bireyin kadın veya erkek olma durumu."),
    ("COŞKU", "Sevinç ve heyebanın güçlü dalgalanması."),
    ("CUDAM", "Aklı kıt, aptal (argoda)."),
    ("CUNTACI", "Ülkeyi silahla, zorla yöneten grubun üyesi."),
    ("CÜBBE", "Hukukçuların ve din adamlarının dış kıyafeti."),
    ("CÜCE", "Boyu normalden çok kısa kalan kişi."),
    ("CÜZDAN", "Para veya kimlik konulan deri / bez kılıf."),
    ("ÇABALAMAK", "Bir işi yapmak için elden gelen gayreti göstermek."),
    ("ÇADIR", "Kumaş ve bezden yapılan sökülebilen portatif sığınak."),
    ("ÇAĞDAŞ", "Aynı çağda yaşayan veya dönemin şartlarına uygun."),
    ("ÇAĞLAYAN", "Suların yüksekten hızla döküldüğü akarsu parçası, şelale."),
    ("ÇAKAL", "Geceleri uluyan kurda benzer yırtıcı yaban köpeği."),
    ("ÇAKIL", "Düzgün, yuvarlak ve ufak dere taşı."),
    ("ÇALGICI", "Geçimini bir enstrüman çalarak kazanan müzisyen."),
    ("ÇALIM", "Kendini gösterişli sunma biçimi, fiyaka veya futbolda adam geçme."),
    ("ÇALIŞKAN", "Sürekli iş gören, boş durmayan gayretli kişi."),
    ("ÇAMAŞIR", "Genellikle içte giyilen ince kıyafet veya yıkanacak elbise."),
    ("ÇAMUKA", "Özellikle Karadeniz yöresine has bir hamsi gibi küçük balık."),
    ("ÇAMUR", "Su ve toprağın yapışkan karışımı."),
    ("ÇANGAR", "Kuşların bir çeşit eski türü."),
    ("ÇANTA", "İçine küçük eşya konulup elde taşınan kap."),
    ("ÇAPKIN", "Geçici aşklar peşinde koşan kişi."),
    ("ÇAPRAZ", "Birbirini eğik kesen, diyagonal, zıt."),
    ("ÇARIK", "Köylülerin giydiği ham deriden ucu kıvrık ayakkabı."),
    ("ÇARPICI", "Çok etkileyici, akılda kalan, sarsıcı."),
    ("ÇARŞAF", "Yatağın üzerine serilen veya kadınların örtündüğü kumaş."),
    ("ÇARŞI", "Dükkânların bulunduğu ana ticaret bölgesi."),
    ("ÇATAL", "Yemek yemekte kullanılan dişli ve saplı alet."),
    ("ÇATIŞMA", "Silahtan silahşa veya karşıt görüşlerin vuruşması, ahenksizlik."),
    ("ÇAVDAR", "Buğdaya benzeyen, dayanıklı serin iklim tahılı."),
    ("ÇAVUŞ", "Askerde onbaşıdan sonra gelen rütbe."),
    ("ÇEKİÇ", "Çivi çakmaya veya esnetmeye yarayan saplı el aleti."),
    ("ÇELME", "Birini düşünmek için ayağına ayak takma numarası."),
    ("ÇEMBER", "Merkeze eşit uzaklıktaki noktaların birleşimi olan halka."),
    ("ÇENGEL", "Nesneleri tutturmaya veya asmaya yarayan kıvrık uçlu demir."),
    ("ÇENTİK", "Ahşap kenarındaki küçük çizik veya yarık."),
    ("ÇERÇEVE", "Resim, ayna vb şeylerin etrafına geçirilen kenarlık."),
    ("ÇEŞİT", "Birbirinden hafif farklılıkları olan türler, nev'i."),
    ("ÇEŞNİ", "Yemeğin içindeki baharatların verdiği ağızda bıraktığı his, aroma."),
    ("ÇEVİK", "Hızlı ve kıvrak hareket edebilen."),
    ("ÇEVRE", "Canlıların yaşamını sürdürdüğü ortam, dolay."),
    ("ÇEYREK", "Dörtte bir oran."),
    ("ÇIĞLIK", "Korkunç, tiz ve yüksek perdeden bağırtı."),
    ("ÇIKAR", "Kişisel fayda, yarar donanımı, menfaat."),
    ("ÇINAR", "Çok kalın gövdeli ve uzun ömürlü ulu bir ağaç türü."),
    ("ÇIRAK", "Mesleği öğrenmek üzere ustanın yanına giren kişi."),
    ("ÇİÇEK", "Bitkilerin üremeye yarayan renkli ve güzel kokulu organı."),
    ("ÇİFTLİK", "Hayvan ve tarım işlerinin yürütüldüğü geniş arazi."),
    ("ÇİLEK", "C vitamini bol, kırmızı, dışı çekirdekli tatlı meyve."),
    ("ÇİMENTO", "Binaları sağlamlaştırmak için kum ve suyla karıştırılan gri toz."),
    ("ÇİZELGE", "Sayıları, bilgileri belirli bir düzende gösteren tablo."),
    ("ÇİZMELİ", "Ayaklarında çizme olan."),
    ("ÇOBAN", "Koyun veya keçi sürülerini otlatıp koruyan kimse."),
    ("ÇOCUK", "Küçük veya ergenlik çağına girmemiş insan yavrusu."),
    ("ÇOĞUL", "İkiden fazla varlığı ifade eden."),
    ("ÇORAP", "Ayağı sıcak tutmak için giyilen örtü."),
    ("ÇORBA", "Yemeklerden önce içilen sulu başlangıç gıdası."),
    ("ÇÖKÜŞ", "Zayıflayıp dağılma, yok olma süreci."),
    ("ÇÖL", "Kumlu, otsuz ve çok kurak devasa arazi."),
    ("ÇÖZÜM", "Bir sorunu halletme, düğümü açma yolu."),
    ("ÇUBUK", "İnce uzun dal veya madeni değnek."),
    ("ÇUKUR", "Çevreye göre daha aşağıda kalan, kazılmış veya doğal oyuk."),
    ("ÇUVAL", "Kaba bez veya plastikten örülmüş büyük taşıma torbasası."),
    ("ÇÜNKÜ", "Zira, sebebi şudur ki bağlacı."),
    ("ÇÜRÜK", "Zamanla bozulan, eski sağlamlığını yitiren nesne."),
    ("DADI", "Evlerde küçük çocukların bakımıyla ilgilenen kadın."),
    ("DAHİLİ", "İçle ilgili olan, içteki."),
    ("DAHİ", "Özel bir akıl ve buluş yeteneğine sahip kimse, deha."),
    ("DAİRE", "Yuvarlak şekil, çemberin içi veya apartman katı."),
    ("DAKİKA", "Bir saatin atmışta biri olan zaman ölçüsü birimi."),
    ("DALGALANMA", "Suda kabarmalar oluşması veya fiyatların sık değişmesi."),
    ("DALGIÇ", "Su altında çalışmak üzere gerekli aletlerle donanmış tüplü kismse."),
    ("DAMAR", "İçinde kanın dolaştığı ince ve uzun boruların her biri."),
    ("DAMAT", "Evlenen erkeğe kız ailesi tarafından verilen ad, güvey."),
    ("DAMLA", "Sıvıların en küçük küresel veya kopan parçası."),
    ("DANIŞMAN", "Bilgisinden, uzmanlığından yararlanmak için başvurulan kimse, müşavir."),
    ("DANTEL", "İplikle değişik motiflerde işlenmiş el örgüsü tül, ağ."),
    ("DARBE", "Hükümeti yasadışı veya zor kullanarak düşürme eylemi veya sert vuruş."),
    ("DAVETİYE", "Toplantıya, düğüne çağırmak amacıyla hazırlanan yazı, basılı kâğıt."),
    ("DAVRANIŞ", "Kişinin her türlü hareketi, tutum, tarz."),
    ("DAYANAK", "Bir şeyi tutan destek, mesnet veya bir sözün asıl kaynağı."),
    ("DEDE", "Babanın ya da annenin babası, büyükbaba."),
    ("DEDİKODU", "Başkası arkasından konuşulan, asılsız veya kötüleyici laf, gıybet."),
    ("DEFNES", "Yaz kış yapraklarını dökmeyen, kokulu yapraklı Akdeniz bitkisi."),
    ("DEFTER", "İçine yazı yazmak, resim yapmak için bir araya getirilmiş kâğıt yaprakları."),
    ("DEĞER", "Bir şeyin hak ettiği paha, önem veya nicelik."),
    ("DEKOR", "Tiyatroda veya mekânda çevreyi yansıtan, süsleyen arka plan eşyaları."),
    ("DELİ", "Aklî dengesi bozulmuş olan, çıldırmış kimse."),
    ("DELİL", "Bir gerçeği ispat etmeye yarayan emare, belge, kanıt."),
    ("DENEYİMLİ", "Bir konuda hayat tecrübesi edinmiş olan, tecrübeli (kişi)."),
    ("DENGE", "Ağırlıkların ya da kuvvetlerin eşit etkide olup hareketsiz kalması, muvazene."),
    ("DENİZALTI", "Su altında hareket edip seyredebilen askeri / araştırma gemisi."),
    ("DEPREM", "Yer kabuğundaki sarsıntılar, zelzele."),
    ("DERECE", "Sıcaklığı veya bir açıyı ölçmekte kullanılan birim."),
    ("DERGİ", "Haftalık, aylık olarak belli aralıklarla çıkarılan yazar yayınları, mecmua."),
    ("DERİN", "Yüzeyi ile dibi arasında fazla mesafe bulunan."),
    ("DESTAN", "Milletlerin kahramanlık maceralarını anlatan manzum büyük edebi eser, epope."),
    ("DESTEK", "Çökmeyi / düşmeyi engelleyen dayanak veya yardım eli."),
    ("DEVE", "Sırtında hörgücü olan, çöllerde yük taşıyan memeli gevişgetiren hayvan."),
    ("DEVLET", "Bir ulusun kendi toprakları üzerinde egemenlik kurduğu siyasi oluşum."),
    ("DEVİR", "Başlangıcı ve sonu belirli bir olayla belirtilen zaman dönemi, çağ."),
    ("DİKKAT", "Duyguları veya idraki bir şeye yöneltme durumu, uyanıklık."),
    ("DİKTATÖR", "Bütün siyasi gücü elinde tutan tek egemen, zorba yönetici."),
    ("DİLİM", "Bir bütünden satırla veya bıçakla kesilerek ayrılmış düz parça."),
    ("DİREKSİYON", "Motorlu taşıtların yönünü kontrol etmeye yarayan çember."),
    ("DİRENÇ", "Bir etkiye karşı koyan kuvvet, rezistans veya ruhsal dayanıklılık."),
    ("DİŞÇİ", "Diş ve ağız hastalıklarını teşhis edip tedavi eden hekim, diş hekimi."),
    ("DİYALOG", "İki kişi arasında geçen karşılıklı konuşma veya oyun metni."),
    ("DİZİN", "Bir kitabın sonunda yer alan kavram haritası veya indeks."),
    ("DOĞA", "İnsan eliyle oluşturulmamış her şeyin yaşam bulduğu çevredir, tabiat."),
    ("DOKTOR", "Tıp okumuş, hastaları iyileştirmeyi meslek edinmiş kimse, tabip, hekim."),
    ("DOLAP", "İçki, yiyecek veya elbise koymaya yarayan göz ve kapağı olan mobilya."),
    ("DOMATES", "Kırmızı renkli, vitamin deposu olan ve salatalarda çok kullanılan sebze (meyve)."),
    ("DONDURMA", "Süt, şeker, meyve vb ile yapılan, soğutularak elde edilen tatlı."),
    ("DOSTLUK", "Samimi, güvene dayalı karşılıklı güzel ilişki ve bağlılık."),
    ("DÖKÜMAN", "Kâğıt üzerinde yazı, belge veya bilgisayardaki metin dosyası."),
    ("DURAK", "Toplu taşıma araçlarının yolcu indirip bindirdiği bekleme alanı."),
    ("DUYGU", "İnsanın kalbinde hissettiği, sevgi, üzüntü vb. ruhani tepkilerin geneli, his."),
    ("ECZACILIK", "İlaç yapımı, satışı ve araştırılması ile ilgilenen dal."),
    ("ECZANE", "İlaç satılan dükkân."),
    ("EDEBİYAT", "Duygu ve düşünceleri kelimelerin estetiği ile anlatan sanat dalı."),
    ("EFENDİ", "Önceleri köle sahiplerini, sonra eğitimli, kibar insanları betimleyen unvan."),
    ("EĞLENCE", "Hoş vakit geçirmek için yapılan aktivite, neşe kaynağı."),
    ("EFSANA", "Çok eski zamanlardan dilden dile aktarılan olağanüstü olayları anlatan masal, mit."),
    ("EGOİST", "Sadece kendini düşünen, bencil kimse."),
    ("EKMEK", "Un ve sudan yapılan ve her sofrada bulunan temel besin."),
    ("EKONOMİ", "Bir ülkenin para, sanayi ve ticaret faaliyetlerinin tümü, iktisat."),
    ("ELBİSE", "İnsanın örtünmesi, korunması veya süslenmesi için giyilen parçalar, giysi."),
    ("EMANET", "Birine geçici olarak korunması için bırakılan değerli şey."),
    ("EMEKLİ", "Belirli bir yaşa ve hizmet gününe ulaşıp çalışma hayatını bitirip maaş alan kimse."),
    ("ENDÜSTRİ", "Hammaddeyi işlemek suretiyle mamul eşya haline çeviren iş sektörü, sanayi."),
    ("ENERJİ", "Bir cismin veya sistemin iş yapabilme kapasitesi veya dinçlik."),
    ("ENTEL", "Birikimini kültürel sahalarda yüzeysel gösterişe çeviren sözde aydın, entelektüelite."),
    ("ESNAF", "Küçük sermaye veya usta zanaatıyla ticaret yapıp geçinen serbest çalışan."),
    ("ESTETİK", "Sanattaki ve doğadaki güzelliğin felsefi incelenişi, güzellik duygusu ölçüsü."),
    ("EŞARP", "Kadınların boyunlarına bağladıkları örtü veya başörtüsü."),
    ("EVLAT", "Anne babanın yetiştirip büyüttüğü yavrusu, çocuğu."),
    ("EVREN", "Gökcisimlerinin ve yıldız sistemlerinin tümünü içeren boşluk, kâinat."),
    ("EVRİM", "Canlıların zaman içerisindeki bedensel değişiklik süreci, tekâmül."),
    ("EYLEM", "Fiil hâli, eylemek, bir olayı gerçekleştirmek."),
    ("FABRİKA", "Makineler ve aletler vasıtasıyla ürünlerin kitle halinde imal edildiği bina tesisi."),
    ("FAİZ", "Borç olarak verilen yatırımlı veya bekletilen paraya getirilen işletim rantı, nema."),
    ("FAKTÖR", "Sonuçlara doğrudan etki eden etken, unsur."),
    ("FARAZA", "Diyelim ki, var say ki, söz gelişi (eski söz)."),
    ("FATURA", "Alışveriş sonrası satılan malın ücretini dökümüyle gösteren resmi belgesi."),
    ("FAYDALI", "Yarar getiren, iyi ve olumlu işlev barındıran şey."),
    ("FECİ", "Acıklı, içe dert ve büyük korku veren, vahim."),
    ("FEDAKAR", "Kendi rahatını veya çıkarlarını başkası için esirgeyen kişi, özverili kimse."),
    ("FELEK", "Gökyüzü, uzay veya talih (halk edebiyatında şans manasında)."),
    ("FELSEFE", "Varlığın, niyetin ve bilginin temellerini veya sorunlarını araştıran akıl bilimi."),
    ("FENER", "İçinde ışık kaynağı olan, aydınlatmaya yarayan saplı veya sapsız kap veya lamba."),
    ("FERAH", "Dar veya sıkıcı olmayan, aydınlık, gönle huzur veren tasarı, durum, his."),
    ("FESAT", "Bozukluk karışıklık yapmaya eğilimli ve insanlar alasını açan kişi veya tavır."),
    ("FETHETMEK", "Bir şehri veya kaleyi askeri güç kullanarak almak, açmak."),
    ("FOTOKOPİ", "Bir yazının, kitabın resim yardımıyla cihaz üzerinde makine kopyası."),
    ("FOTOĞRAF", "Işığın objektif ile kaydedilip görüntü elde edilmesi sanatı veya elde edilen nesne.")
]


count = 0
next_id = len(db) + 1

for ans, clo in new_words:
    ans_upper = ans.upper().replace('İ', 'I')
    if ans_upper not in existing_words and 5 <= len(ans_upper) <= 13:
        diff = "medium" if len(ans_upper) <= 6 else "hard"
        level = random.randint(3, 5) if diff == "medium" else random.randint(6, 9)
        db.append({
            "id": f"tr_kw_{next_id:04d}",
            "type": "crossword_clue",
            "difficulty": diff,
            "level": level,
            "answer": ans_upper,
            "answerLength": len(ans_upper),
            "category": "Genel Kültür",
            "clue": clo,
            "tags": [f"{len(ans_upper)}-harf", "orta" if diff=="medium" else "zor", "genel", "yeni-sorular-tdk"],
            "createdAt": "2026-02-25"
        })
        existing_words.add(ans_upper)
        next_id += 1
        count += 1

with open(db_path, "w", encoding="utf-8") as f:
    json.dump(db, f, indent=2, ensure_ascii=False)

print(f"Added {count} extremely high quality manual dictionary words to the DB.")
