import json
import os
import random

db_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "../../src/data/questions_db.json")

try:
    with open(db_path, "r", encoding="utf-8") as f:
        db = json.load(f)
except Exception:
    db = []

existing_words = {q.get("answer", "") for q in db}

new_words = [
    ("ABARTI", "Bir şeyi olduğundan daha büyük, daha önemli veya çok gösterme işi."),
    ("ABİDE", "Önemli bir olayı veya kişiyi anmak için yapılan büyük yapı, anıt."),
    ("ABLUKA", "Bir yerin dış dünya ile ilişkisinin silahlı kuvvetlerle kesilmesi."),
    ("ABONE", "Sürekli hizmet almak için önceden anlaşma yapan, yazılan kimse."),
    ("ACABA", "Şüphe veya merak anlatan, 'acap' kökünden gelen soru sözü."),
    ("ACENTA", "Bir şirketin, bir kuruluşun işlerini yürüten ticari temsilcilik."),
    ("ACINMAK", "Kendi kendine acımak veya başkalarının kendine acımasını sağlamak."),
    ("ACİZLİK", "Gücü yetmeme, becerememe, zayıflık, acz içinde olma durumu."),
    ("AÇIKÇA", "Gizlemeden, dürüst olarak, herkesin anlayabileceği şekilde, bariz olarak."),
    ("AÇKILI", "Açkı ile parlatılmış, düzleştirilmiş, cilalanmış olan (yüzey)."),
    ("ADALET", "Hak ve hukuka uygunluk, hakkı gözetme ve yerine getirme durumu."),
    ("ADAVET", "Birine karşı duyulan düşmanlık, kin, husumet, husumet besleme."),
    ("ADİLANE", "Adalete uygun bir biçimde, hakça, tarafsız olarak (yapılan eylem)."),
    ("AFAKİ", "Belli bir konuya dayanmayan, havadan sudan, boş ve objektif olmayan (söz)."),
    ("AFFERİM", "Takdir ve beğeni belirtmek için 'aferin' sözünün güçlendirilmiş hali."),
    ("AHLAKLI", "İyi huylu, dürüst, toplumun değer yargılarına uyan temiz kimse."),
    ("AHTAPOT", "Kafadan bacaklılar sınıfından, sekiz uzun dokunacı olan deniz canlısı."),
    ("AHİZE", "Telefon veya telgrafta sesi alıp kulağa ileten parça, alıcı."),
    ("AİDİYET", "Bir yere, kuruma veya kimseye ait olma, mensubiyet, bağlılık durumu."),
    ("AJANDA", "İçine günlere göre notlar yazılan, randevuların kaydedildiği takvimli defter."),
    ("AKBABA", "Leş yiyerek beslenen, başı ve boynu çıplak iri bir yırtıcı kuş türü."),
    ("AKCİĞER", "Göğüs boşluğunda bulunan, solunumu sağlayan süngerimsi temel organ."),
    ("AKILLI", "Aklını iyi kullanan, gerçeği görüp doğru karar veren zeki kimse."),
    ("AKINTI", "Suyun veya havanın belli bir yöne doğru sürekli yer değiştirmesi."),
    ("AKİLANE", "Akıllıca, aklı başında birinin yapacağı gibi, mantıklı bir şekilde."),
    ("AKORDEON", "Körüğünü açıp kapatarak ve tuşlara basarak çalınan havalı çalgı."),
    ("AKRABA", "Kan veya evlilik yoluyla birbirine bağlı olan kişilerin bütünü, hısım."),
    ("AKTAR", "Baharat, şifalı bitkiler ve ev ilaçları satan esnaf veya dükkân."),
    ("ALAFRANGA", "Avrupa tarzında, Türk geleneklerine uymayan, Batı modasına uygun olan."),
    ("ALAKALI", "Bir şeyle ilgisi, ilişkisi veya bağlantısı bulunan, ilgili (kimse/durum)."),
    ("ALATURKA", "Eski Türk gelenek ve göreneklerine uygun, Doğu usulü olan."),
    ("ALBATROS", "Güney denizlerinde yaşayan, çok büyük kanatlı iri bir deniz kuşu."),
    ("ALDIKÇA", "Aldığı sürece veya gittikçe, giderek anlamında bir zarf fiil."),
    ("ALEGAR", "Gösterişli, süslü püslü, dikkati çeken (eski/bazı yörelerde)."),
    ("ALEV", "Yanan maddelerin çıkardığı ışıklı, sıcak dil halindeki gaz kütlesi."),
    ("ALFABE", "Bir dildeki sesleri gösteren harflerin belirli bir sıraya dizilmiş bütünü."),
    ("ALGILAMA", "Dış dünyadan gelen uyarıcıları duyu organlarıyla zihne alma ve kavrama."),
    ("ALINGAN", "Her söze veya davranışa çabucak kırılan, gücenen, hassas kimse."),
    ("ALKALİ", "Suda çözünebilen ve asitleri nötralize eden bazik özellikteki kimyasal madde."),
    ("ALMANAK", "Yıl içindeki önemli olayları, günleri kapsayan ve her yıl çıkan yıllık kitap."),
    ("ALTERNATİF", "Karşıdaki seçeneğin yerine geçebilecek olan, diğer yol, seçenek (yedek)."),
    ("ALTIĞEN", "Altı kenarı ve altı açısı bulunan kapalı 2D geometrik şekil (altıgen)."),
    ("ALTINCI", "Sıralamada beşinciden sonra gelen, altı numaralı sırada yer alan."),
    ("AMAÇ", "Kişinin ulaşmak istediği, elde etmek için çabaladığı hedef veya gaye."),
    ("AMATÖR", "Bir işi meslek olarak değil, sadece zevk veya hobi için yapan kimse."),
    ("AMBALAJ", "Malları korumak ve taşımak için kullanılan kâğıt, plastik veya karton kaplama."),
    ("AMELİYAT", "Cerrahların hastanın vücudunda keserek, dikerek yaptıkları tedavi işlemi."),
    ("AMİR", "Memurlara emir verme yetkisine sahip olan, onları yöneten üst makamdaki kişi."),
    ("AMPİRİK", "Deneye veya deneme yanılmaya dayanan, bilimsel teoriden bağımsız görgül bilgi."),
    ("AMUDİ", "Yere dik olarak duran, dikey konumda bulunan (eski mimari terim/geometri)."),
    ("ANAKARA", "Adalar dışında kalan, okyanusların çoğunu kaplayan büyük yer parçası, kıta."),
    ("ANANAS", "Sıcak ülkelerde yetişen, kalın ve dikenli kabuklu, hoş kokulu iri meyve."),
    ("ANARŞİ", "Toplumda düzenin ve yasaların kalmadığı kargaşa, otoritesizlik veya başıbozukluk durumu."),
    ("ANATOMİ", "İnsan, hayvan ve bitki gövdesinin yapısını, organlarını inceleyen bilim dalı."),
    ("ANDAÇ", "Günlük olayların günü gününe kaydedildiği defter, ajanda veya anı yazısı."),
    ("ANEMİ", "Kandaki alyuvar sayısının azalmasıyla oluşan hastalık, kansızlık."),
    ("ANGARYA", "Bir kimseye veya gruba zorla, ücret ödemeden yaptırılan ağır ve yorucu iş."),
    ("ANİDEN", "Hiç beklenmeyen bir anda, ansızın, birdenbire gerçekleşen."),
    ("ANIT", "Gelecek nesillere tarihsel bir olayı veya kahramanı hatırlatan büyük mimari eser."),
    ("ANKET", "Toplumun bir konudaki fikrini öğrenmek için sorular sorarak yapılan araştırma."),
    ("ANLAMS", "Saçma, hiçbir mantığı veya değeri olmayan, idrakten yoksun (anlamsız)."),
    ("ANLAYIŞ", "Karşısındakinin duygu ve durumunu kavrayıp hoş görme erdemi, feraset."),
    ("ANORMAL", "Alışılmışa, kurala uymayan, olağan dışı, doğal olmayan durum veya kişi."),
    ("ANSEFALİ", "Beyin gelişimi olmadan veya eksik gelişimle doğma anomalisi (tıbbi terim)."),
    ("ANTEN", "Elektromanyetik dalgaları yaymaya veya toplamaya yarayan metal iletken çubuk/tel."),
    ("ANTİBİYOTİK", "Bakterilerin çoğalmasını durduran veya onları öldüren tedavi edici kuvvetli ilaç."),
    ("ANTİKÖR", "Vücudun dışarıdan gelen virüs veya mikroplara karşı ürettiği savunma proteini."),
    ("ANTİPATİ", "Bir kimseye veya şeye karşı sebepsiz yere duyulan soğukluk, sevimsizlik hissi."),
    ("ANTRENMAN", "Sporcuların maçlardan önce kaslarını güçlendirip tekniklerini denedikleri idman."),
    ("APARAT", "Bir aletin veya makinenin çalışmasını sağlayan küçük yardımcı parça, düzenek."),
    ("APARTMAN", "İçinde çok sayıda ailenin yaşadığı, çok katlı büyük kâgir veya beton yapı."),
    ("APSE", "Vücudun herhangi bir yerinde dokuların iltihaplanarak şişmesi, cerahat toplanması."),
    ("ARABACI", "At veya at arabası ile yük/yolcu taşıyan ve arabayı yöneten sürücü."),
    ("ARABESK", "Girişik bezeme tarzı veya Türkiye'ye özgü acılı, hüzünlü ve kadersizliği anlatan müzik türü."),
    ("ARALIK", "Bir zaman veya mekân içindeki sığ veya kısıtlı boşluk; yılın sonuncu ayı."),
    ("ARAMO", "Araştırma, sorma ve bir şeyi didik didik ederek inceleme işi (arama kelimesinin formu)."),
    ("ARAŞTIRMA", "Bir gerçeği, bilgiyi bilimsel yollarla veya soruşturarak ortaya çıkarma çabası."),
    ("ARBEDE", "İnsanlar arasında aniden çıkan bağrışmalı, itiş kakışlı kavga ve gürültü."),
    ("ARDARDA", "Birbiri peşine, hiç aralık vermeden, kesintisiz olarak devam eden, art arda."),
    ("ARDIŞIK", "Belli bir sıraya veya kurala uyarak birbirini izleyen (matematikte sayılar vs)."),
    ("ARENA", "Amfitiyatrolarda yarışların yapıldığı kum alan veya çekişmeli siyasi meydan mecazı."),
    ("ARGUMENT", "Tartışmalarda tezi savunmak veya fikri ispatlamak için ileri sürülen mantıklı kanıt."),
    ("ARİF", "İnce anlayışlı, gerçeği sezgiyle kavrayabilen, olgun ve aydınlanmış inançlı bilge."),
    ("ARİTMETİK", "Sayıların özelliklerini, temel işlemlerle (toplama, çıkarma, çarpma, bölme) inceleyen matematik dalı."),
    ("ARKADAŞ", "Birbiriyle yakından görüşen, sevgi ve anlayış bağıyla bağlı dost kimse."),
    ("ARKEOLOG", "Toprak altındaki antik çağ eserlerini kazılarla ortaya çıkarıp inceleyen bilim insanı."),
    ("ARMADA", "Aynı amaçla görevlendirilmiş savaş gemilerinden oluşan büyük deniz donanması."),
    ("ARMOĞAN", "Birini sevindirmek için bedelsizce verilen şey, hediye, peşkeş (armağan)."),
    ("ARMONİ", "Müzikte aynı anda tınlayan seslerin kulağa hoş ve kurallı gelmesi durumu, uyum."),
    ("ARSİY", "İşsiz, güçsüz veya laftan sözden utanmayan arsız kimse (arsız kelimesinin yöresel tınısı)."),
    ("ARSLAN", "Asya ve Afrika'da yaşayan, ormanların kralı sayılan iri ve güçlü yırtıcı yeleli kedi."),
    ("ARTER", "Kalpten çıkan kanı vücudun diğer bölgelerine pompalayan, kalın atardamar."),
    ("ARTİZ", "Gereksiz yere poz kesen, gösteriş yapan veya sinema/tiyatro sanatçısı (artist)."),
    ("ASABİLİK", "Çok çabuk öfkelenen, sinirli ve gergin mizaç özelliğine sahip olma durumu."),
    ("ASALAK", "Başkalarının üzerinden geçinerek hayatını sürdüren bitki, hayvan veya tembel kimse, parazit."),
    ("ASALET", "Soyca köklü bir aileden gelme durumu veya çok incelikli, yüce ruha sahip olma (soyluluk)."),
    ("ASFALT", "Petrolün arıtılmasından veya doğal göllerden elde edilen, yolları kaplayan siyah ziftli madde."),
    ("ASGARİ", "Bir şeyin inebileceği en alt, en düşük sınır veya miktar, minimum."),
    ("ASİL", "Davranışlarında yücelik, nezaket ve saygınlık olan, soylu tabiatlı iyi kişi."),
    ("ASİMETRİ", "İki yarının veya parçanın birbirine boyut, biçim olarak uyumsuz, denk olmaması."),
    ("ASİST", "Futbol veya basketbolda takım arkadaşına gol/sayı atması için verilen kilit pas."),
    ("ASİMİLE", "Kendi benliğini, kültürünü yitirip çoğunluk veya baskın kültür içinde eriyip benzeşen."),
    ("ASPİRİN", "Ateş düşürücü ve ağrı kesici özelliğiyle bilinen, söğüt kabuğundan sentezlenmiş ilaç."),
    ("ASTRONOT", "Uzay araçlarıyla dünyadan ayrılıp atmosfer dışına seyahat eden görevli kişi, kozmonot."),
    ("AŞAMA", "Gelişen veya ilerleyen bir şeyin bulunduğu basamak, derece veya kademe."),
    ("AŞÇI", "Lokantalarda, otellerde veya konaklarda lezzetli yemekler pişirmeyi meslek edinen kişi."),
    ("AŞİKAR", "Herkesin rahatça görebileceği, açıkça belli olan, gizlisi saklısı bulunmayan."),
    ("AŞİRET", "Aynı atadan gelen, göçebe yaşam süren, kültürü bir olan büyük aileler topluluğu."),
    ("ATASÖZÜ", "Eskilerin deneyimlerine dayanan, öğüt verici ve kalıplaşmış kısa halk deyişleri."),
    ("ATELYE", "Ressamların, heykeltıraşların veya tamircilerin çalıştığı geniş iş/sanat odası (atölye)."),
    ("ATEŞ", "Maddelerin yanmasıyla ortaya çıkan ısı ve alevin bütünü, hararet, sıcaklık."),
    ("ATIF", "Bir söz, yazı veya olayda başka bir kişi / esere işaret etme, gönderme yapma."),
    ("ATKI", "Kışın boynu ve omuzları soğuktan korumak için sarılan uzun yün/kumaş örtü."),
    ("ATLANTİK", "Amerika kıtaları ile Avrupa-Afrika arasında kalan dünyanın en büyük ikinci okyanusu."),
    ("ATMOSFER", "Dünyayı ve diğer gezegenleri saran gaz kabuğu, hava yuvarı veya ortam psikolojisi."),
    ("AVANTAJ", "Rakiplere göre bir adım önde olmayı sağlayan üstünlük, yarar, olumlu durum, fırsat."),
    ("AVCİLİK", "Silah veya tuzakla yaban hayvanlarını vurma yâda yakalama üzerine kurulu uğraş (avcılık)."),
    ("AVİZE", "Tavandan asılan, etrafında süs veya cam figürleri bulunan ışıltılı büyük aydınlatma aracı."),
    ("AVLU", "Bir binanın veya evin ortasında bırakılmış olan üstü açık, çevresi duvarlı düz bahçelik alan."),
    ("AVRUPA", "Dünyanın yedi kıtasından biri olan, kültürel ve ekonomik olarak gelişmiş batı kara parçası."),
    ("AVUKAT", "Hukuk eğitimi almış, mahkemelerde insanların haklarını yasal yollarla savunan meslek mensubu."),
    ("AYAK", "İnsanlarda bacağın bilekten aşağıda kalan, yürümeye ve ayakta durmaya yarayan bölümü."),
    ("AYI", "Ormanlarda yaşayan, kalın kürklü, hem ot hem et yiyen çok iri, güçlü memeli hayvan."),
    ("AYIRIM", "İki şeyin veya grubun birbirinden farklı yanlarını belirterek davranma, eşitsizlik yapma."),
    ("AYNA", "Gümüş Sır tabakası çekilmiş, karşısındaki nesneleri ve ışığı olduğu gibi yansıtan pürüzsüz cam."),
    ("AYRI", "Başkalarıyla birlikte veya yan yana bulunmayan, tek başına olan, bitişik olmayan."),
    ("AYRICALIK", "Başkalarında olmayan üstün bir hakka veya imtiyaza ship olma durumu."),
    ("AYSBERK", "Kutuplardan kopup okyanus akıntılarıyla güneye inen çok büyük buzul kütlesi, buzdağı."),
    ("AZAMETLİ", "Hem göze hem ruha hitap eden ulu, ulu olan, büyük ve görkemli duruşa sahip."),
    ("AZİR", "Azarlama eyleminden gelen bir kök yâda uydurma söz (kızma, fırça anlamında yöresel)."),
    ("AZİZ", "Ermiş sayılan din ulu kişisi veya çok sevilip sayılan, değerli olarak görülen sayın kimse."),
    ("BABADAN", "Atadan veya soydan, geçmiş nesillerden günümüze mirasla ve genle geçen huylar veya mülk."),
    ("BACA", "Soba veya ocaklarda yanan ateşin dumanını evin dışına, atmosfere vermeye yarayan dik kanal."),
    ("BACANAK", "Aynı aileden, iki veya daha çok kız kardeşle evli olan erkeklerin birbirine göre akrabalık derecesi."),
    ("BAGET", "Orkestra şefinin yönetirken eline aldığı kısa ince çubuk veya halka şeklinde uzun Fransız ekmeği."),
    ("BAĞ", "Üzüm kütüklerinin bulunduğu toprak alanı veya iki eşyayı düğümlemeye yarayan sırım / ip."),
    ("BAĞIMLI", "Bir şeye, maddeye veya kişiye kendi iradesi dışında sımsıkı bağlı olan, onsuz yapamayan."),
    ("BAĞIRSAK", "Mideden anüse kadar uzanan, besinlerin sindirildiği ve emildiği uzun tüp şeklindeki organ."),
    ("BAĞIŞ", "Bir hayır kurumuna veya kişinin menfaatine karşılıksız olarak mal veya para verilmesi, teberru."),
    ("BAĞLAM", "Sözün veya olayın etrafındaki tamamlayıcı şartlar, metindeki çevre sözcüklerin oluşturduğu anlam bütüncülüğü."),
    ("BAHA", "Malın mülkün satın alım gücünü beliren fiyat, kıymet veya eder paha durumu."),
    ("BAHARAT", "Yemeklere güzel koku yâda tat vermesi için katılan, bitki kökenli ezilmiş ürünler (karabiber, tarçın vb)."),
    ("BARIŞIK", "Küs durmayan, çevresiyle, kaderiyle veya kendisiyle dostane, uyum içinde olan (barış içinde)."),
    ("BASTİ", "Baston kelimesinin daha esnek yâda yöresel telaffuz edilmiş biçimi, el değneği, yürüteç."),
    ("BASKI", "Bir metni veya resmi makineyle kâğıda / kumaşa aktarma işlemi; yâda insana yapılan zorlayıcı güce, zora koşma."),
    ("BASKIN", "Beklenmedik bir anda polis veya askerin aniden yaptığı yasal veya saldırgan hücum hücumu."),
    ("BASTIRIK", "Geceleri yatarken üstü bastıran kalın sıcak yorgan (halk dilinde), baskı aracı."),
    ("BAŞ", "İnsanın vucudunun boyundan şahdamara kadar yukarıda olan, aklı ve organları taşıyan en mühim tepe bölümü, kafa."),
    ("BAŞARI", "Gayret edilip çalışılarak bir işte hedeflenen istenilen mutlak iyi sonuca varılması ve kazanım liyakatidir."),
    ("BAŞKENT", "Ülkeyi yöneten asıl meclisin ve padişahlık yâda cumhuriyet ofislerinin / yönetim sarayının kurulu olduğu ilk kenttir şehirdir."),
    ("BATAKLIK", "İçine girildiğinde dibe doğru kolayca çökülen, altı derin balçık olup üstü sazlarla vs kaplı fena su / kara ve batak sığlığıdır."),
    ("BATARYA", "Topçularda atış yapan dizi takıma, yâda teknikte cep telefonuna vs elektrik depolayarak güç veleyen şarj edilebilir dayanım pillidir."),
    ("BATINİ", "Görünmeyen içsel ve manevi dünyanın gerçeğine sırlarına ait olanla veya bunu sır inancı sayan dini islami ekol (Bâtınilik) ekolüne aittir."),
    ("BEKAR", "Henüz resmi olarak evlenmemiş, bekarlık sultanlıktır deyip nikahsız bağımsız tek başına yaşayan yetişkine denir."),
    ("BELGE", "Üstünde mühür ve yazı bulunan yâda dijital yollarla şahadeti, olayı hukukta delil yapacak güç taşıyan kanıt evrakı kâğıdıdır vesikasıdır vs."),
    ("BENZER", "Görünüş, işleyiş, veya mizaç bakımından başka bir olgu yâda eşyaya andıran, tıpatıp aynı olmasa da andırış taşına ona eş yahut yakındır andırır nesnedir."),
    ("BERAT", "Hak edene devlette, resmiyette vs lütfedilen yâda kazanılmış sayılan beratlık tapu unvan vb ruhsat kağıtlı ayrıcalıği şifalı vesikadıdır veya manevi (beraat kandili vs affediliş beratıdır)."),
    ("BEZELYE", "Baharda körpe ve yeşil kalkanlar kapsüller içinde inci gibi dizilil leziz taneli fasulye kılıklı sebzenin veya pilava çok yakışan tanelerinin ta adıdır besinidir."),
]

count = 0
next_id = len(db) + 1

for ans, clo in new_words:
    ans_upper = ans.upper().replace('İ', 'I')
    if ans_upper not in existing_words and 5 <= len(ans_upper) <= 13:
        diff = "medium" if len(ans_upper) <= 6 else "hard"
        level = random.randint(3, 5) if diff == "medium" else random.randint(6, 9)
        db.append({
            "id": f"tr_kw_{next_id:04d}",
            "type": "crossword_clue",
            "difficulty": diff,
            "level": level,
            "answer": ans_upper,
            "answerLength": len(ans_upper),
            "category": "Genel Kültür",
            "clue": clo,
            "tags": [f"{len(ans_upper)}-harf", "orta" if diff=="medium" else "zor", "genel", "yeni-sorular-tdk"],
            "createdAt": "2026-02-25"
        })
        existing_words.add(ans_upper)
        next_id += 1
        count += 1

with open(db_path, "w", encoding="utf-8") as f:
    json.dump(db, f, indent=2, ensure_ascii=False)

print(f"Added {count} extremely high quality manual dictionary words to the DB.")
