import json
import os
import random

db_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "../../src/data/questions_db.json")

try:
    with open(db_path, "r", encoding="utf-8") as f:
        db = json.load(f)
except Exception:
    db = []

existing_words = {q.get("answer", "") for q in db}

new_words = [
    ("MABERA", "Öte yanı, arka tarafı (eski dilde)."),
    ("MACERA", "Baştan geçen ilginç, heyecanlı ve tehlikeli olaylar zinciri."),
    ("MADALYA", "Yarışmalarda derece alanlara verilen metal ödül."),
    ("MADENCİ", "Yer altından kömür, altın gibi madenleri çıkaran işçi."),
    ("MAHBUDE", "Sevgili kadın, sevilen kadın."),
    ("MAHKEME", "Adaletin ve hukukun sağlandığı, davaların görüldüğü resmi yer."),
    ("MAHLAS", "Şairlerin veya yazarların kullandığı takma ad."),
    ("MAHŞER", "Kıyamet günü ölülerin dirilip toplanacağı büyük alan."),
    ("MAKALE", "Bir konuyu açıklamak veya savunmak için yazılan gazete/dergi yazısı."),
    ("MAKARA", "Üzerine iplik, tel gibi şeylerin sarıldığı tekerlek biçiminde araç."),
    ("MAKET", "Bir yapının, aracın veya eserin orantılı küçük modeli."),
    ("MAKSAT", "Ulaşılmak istenen sonuç, niyet, gaye, amaç."),
    ("MALUMU", "Bilinen, herkesçe malum olan gerçek."),
    ("MANDAL", "İpe asılan çamaşırları tutturmaya yarayan kıskaçlı alet."),
    ("MANEVİ", "Maddi olmayan, ruhsal, içsel olan değer."),
    ("MANGAL", "İçinde kömür ateşi yakılarak et pişirilen veya ısınılan taşınabilir ocak."),
    ("MANKEN", "Vitrinlerde giysi sergilemeye yarayan insan biçiminde model."),
    ("MANTIK", "Doğru düşünme sanatı ve bilimi, akıl yürütme yolu."),
    ("MANYETİK", "Mıknatıs özelliği taşıyan, çekim gücü olan."),
    ("MANZARA", "Gözün görebildiği alan, doğa veya şehir görünümü."),
    ("MASÖR", "Bedeni yollara, kaslara masaj yaparak rahatlatan erkek kişi."),
    ("MATBAA", "Kitap, gazete, dergi gibi yayınların basım evi."),
    ("MAYINLI", "İçine mayın döşenmiş patlamaya hazır alan."),
    ("MAZERET", "Bir hatayı hoş göstermek için ileri sürülen haklı sebep."),
    ("MEÇHUL", "Bilinmeyen, kimliği veya nerede olduğu belirsiz olan."),
    ("MEDENİ", "Uygarlığa ulaşmış, şehirli, kaba ve ilkel olmayan."),
    ("MEHTAP", "Açık gecelerde ayın yaydığı parlak ve romantik ışık."),
    ("MEKANİK", "Kuvvetlerin madde üzerindeki etkisini inceleyen fizik dalı veya makineyle olan."),
    ("MENDİL", "Burun silmek, el kurulamak için kullanılan küçük kumaş parçası."),
    ("MERASİM", "Önemli günlerde yapılan tören, kutlama."),
    ("MERHABA", "Geniş ve rahat yerde olasın anlamına gelen en yaygın selamlama sözü."),
    ("MERMER", "Heykel ve inşaatta kullanılan, sertleşmiş kireç taşı, somaki."),
    ("MESAFE", "İki nokta veya şey arasındaki uzaklık, aralık."),
    ("MESANE", "İdrarın böbreklerden gelip biriktiği torba, idrar kesesi."),
    ("MESELE", "Çözülmesi gereken sorun, problem."),
    ("MESLEK", "Geçim sağlamak için yapılan sürekli iş, uğraş."),
    ("MERHAMET", "Bir kimsenin veya canlının acısına ortak olup ona iyilik etme duygusu."),
    ("MİĞFER", "Savaşta askerlerin başını koruyan demir veya çelik başlık."),
    ("MİHMAN", "Çok eskiden misafir, konuk anlamına gelen sözcük."),
    ("MİKAİL", "Dört büyük melekten doğa olaylarını yönetmekle görevli olanı."),
    ("MİKTAR", "Bir şeyin sayılabilen, ölçülebilen derecesi veya büyüklüğü."),
    ("MİKROP", "Hastalıklara yol açan, gözle görülemeyen küçük organizma."),
    ("MİLLET", "Aynı topraklar üzerinde yaşayan, dili ve kültürü ortak olan insan topluluğu."),
    ("MİLYAR", "Binin bir milyonu, 10 üzeri 9 sayısının adı."),
    ("MİMARİ", "Binaları tasarlama, estetik ve sağlam inşa etme sanatı."),
    ("MİNBER", "Camilerde imamın hatbe okumak için çıktığı merdivenli yer."),
    ("MİNE", "Dişlerin veya metal eşyaların üzerindeki sert parlak tabaka."),
    ("MİRAS", "Bir kimsenin ölümünden sonra varislerine kalan mal mülk."),
    ("MİSAFİR", "Bir evde veya yerde kısa süreliğine ağırlanan konuk."),
    ("MİTOLOJİ", "Bir halkın tanrılarını ve kahramanlarını anlatan söylenceler bilimi."),
    ("MODERN", "Çağcıl, yeniliğe ayak uydurmuş, eski geleneklerden uzak olan."),
    ("MOTOR", "Yakıt veya elektrik enerjisini mekanik enerjiye çeviren makine."),
    ("MUAMMA", "Anlaşılmayan, çözülmesi veya bilinmesi çok zor olan sırlı durum."),
    ("MUCİZE", "İnsan aklının sınırlarını aşan, doğaüstü ve şaşırtıcı dini olay."),
    ("MUHTEŞEM", "Görkemli, göz kamaştıran, çok etkileyici ve büyük olan."),
    ("MÜJDE", "Beklenen veya sevilen, sevindirici ve iyi haber."),
    ("MÜZİKAL", "Şarkı ve dansların iç içe geçtiği tiyatro veya film türü."),
    ("NAFAKA", "Boşanan eşlerin birbirine veya çocuklara mahkemece bağlanan aylığı."),
    ("NAKKAŞ", "Kitap sayfalarına minyatür sanatıyla resim yapan sanatçı, bezeyici."),
    ("NAKLİYE", "Eşya, yük veya yolcu taşıma işi."),
    ("NAMKÖR", "Gördüğü iyiliği bilmeyen, vefasız veya iyiliğe kötülükle cevap veren kimse."),
    ("NAMZET", "Bir görev veya makam için aday olan kimse."),
    ("NARİN", "İnce yapılı, zarif, kaba ve iri olmayan."),
    ("NASİHAT", "Doğru yolu göstermek, ders vermek için söylenen eğitici söz, öğüt."),
    ("NATÜREL", "Doğada bulunduğu gibi olan, yapay veya sahte olmayan, doğal."),
    ("NAZAR", "Kıskanç ve kötü bakışın sebep olduğuna inanılan hastalık, göz değmesi."),
    ("NEBAT", "Toprakta yetişen her türlü bitki."),
    ("NEDEN", "Bir şeyin olmasına yol açan faktör, sebep."),
    ("NEFES", "Solunum sırasında akciğerlere doldurulup boşaltılan hava."),
    ("NEFRET", "Birine karşı duyulan aşırı sevgisizlik, tiksinme ve öfke duygusu."),
    ("NEMRUT", "Yüzü gülmeyen, acımasız ve sert bakışlı kimse (mitolojik bir kraldan)."),
    ("NERGİS", "Soğanlı, güzel kokulu, ilkbaharda açan sarı/beyaz çiçekli süs bitkisi."),
    ("NESİL", "Aynı yıllarda doğmuş ve aynı çağın şartlarını yaşamış kuşak."),
    ("NETİCE", "Bir eylemin, sürecin veya araştırmanın vardığı son durum, sonuç."),
    ("NEVİR", "Yüz rengi, beniz, hal, derman."),
    ("NEZAKET", "Başkalarına saygılı, kibar ve ince davranma kuralı."),
    ("NİDA", "Korku, heyecan veya sevinç anlarında çıkarılan sesşendirme, ünlem."),
    ("NİHAYET", "En sonunda, son, bitiş."),
    ("NİKAP", "Kadınların yüzlerini örtmek için kullandıkları peçe."),
    ("NİSPET", "Bir şeyin başka bir şeye oranı veya birini kıskandırma hareketi."),
    ("NİŞAN", "Evlenmeden önce çiftlerin yüzük takarak sözlenmesi veya devlete ait madalya."),
    ("NOBRAN", "Davranışları kaba, kırıcı, sert ve şımarık olan, nobranlık."),
    ("NOKTA", "Cümle sonuna konan işaret veya kalemin kâğıtta bıraktığı küçük iz."),
    ("NOTER", "Hukuki işlemleri ve belgeleri yasal olarak onaylayan memur."),
    ("NÖBETÇİ", "Sırayla belirli bir zaman diliminde beklemekle görevli kişi."),
    ("NUMUNE", "Bir şeyin tamamını temsil eden veya kalitesini gösteren küçük örnek."),
    ("NURANİ", "Yüzünden, halinden ışık fışkıran, aydınlık, temiz ve ermiş görünümlü kişi."),
    ("NÜFUS", "Bir ülke veya bölgede yaşayan insanların toplam sayısı."),
    ("NÜKTE", "İnce anlamlı, düşündürücü ve güldürücü zarif şaka."),
    ("OBA", "Göçebe aşiretlerin konakladıkları çadırlardan oluşan büyük kamp."),
    ("OBJE", "Felsefe ve sanatta ele alınan, düşünceye konu olan nesne."),
    ("OCAK", "Ateş yakılarak yemek pişirilen veya ısınmaya yarayan düz düzenek, yılın ilk ayı."),
    ("ODAK", "Işık/ısı ışınlarının toplandığı merkez nokta, mihrak."),
    ("ODUN", "Ağaçların kesilerek yakacak veya inşaat malzemesi haline getirilmiş gövdesi."),
    ("OĞUL", "Erkek evlat."),
    ("OKYANUS", "Kıtaları birbirinden ayıran dünyanın en büyük ve derin tuzlu su kütlesi."),
    ("OLAY", "Toplumda veya doğada meydana gelen ilgi çekici vaka, hadise."),
    ("OMUZ", "Boyun ile kolların birleştiği, yük taşımaya uygun eklem bölgesi."),
    ("ONUR", "İnsanın kendine duyduğu büyük saygı, haysiyet, şeref."),
    ("OPERA", "Sözlerinin tamamı şarkı olarak senfonik orkestrayla söylenen müzikli oyun."),
    ("OPTİK", "Işığın doğasını ve görme olayını inceleyen fizik branşı."),
    ("ORMAN", "Çok sayıda ulu ağacın ve yaban hayatının birlikte bulunduğu yeşil alan."),
    ("ORTAK", "Bir işi, malı veya kârı beraber paylaşan hissedarlardan her biri."),
    ("ORUÇ", "Dini inanç gereği güneşin doğuşundan batışına kadar yemek/içmekten kesilme ibadeti."),
    ("OTEL", "Yolcuların geçici olarak konaklamasını ve yemeğini sağlayan büyük tesis."),
    ("OTLAK", "Hayvan sürülerinin otlayıp karınlarını doyurabilmesi için uygun çayır, mera."),
    ("OTOBAN", "Şehirlerarasında hızlı ulaşıma uygun, genelde paralı geniş otoyol."),
    ("OTORİTE", "Devletin veya bir kişinin yaptırım yapabilme gücü, emretme kudreti, yetke."),
    ("OYUN", "Vakit geçirmek, eğlenmek için kurallar çerçevesinde yapılan faaliyet."),
    ("OZAN", "Duygularını ve düşüncelerini saz çalarak müzikle anlatan eski halk şairi."),
    ("ÖBEK", "Aynı türden canlı veya cansız nesnelerin oluşturduğu küçük yığın, grup."),
    ("ÖÇ", "Kendisine zarar verene aynısıyla karşılık verme duygusu, intikam."),
    ("ÖDÜL", "Bir başarı, iyilik karşılığında onurlandırmak amacıyla verilen madalya veya armağan."),
    ("ÖFKE", "Kızgınlık, hiddet veya tahammülsüzlük hissinin şiddetli gösterimi."),
    ("ÖĞRENCİ", "Okula, kursa vb. bir eğitim kurumuna gidip eğitim alan kimse, talebe."),
    ("ÖĞRETMEN", "Mesleği bilgi öğretmek ve öğrenci yetiştirmek olan eğitmen, muallim."),
    ("ÖKÜZ", "Etinden gücünden yararlanılan büyükbaş evcil hayvan veya çok anlayışsız kişi."),
    ("ÖLÇEK", "Haritada veya planlardaki küçültme oranı veya tartı birimi."),
    ("ÖMÜR", "Doğumdan ölüme kadar geçen zaman dilimi, haya süresi."),
    ("ÖNDER", "Toplumu, bir grubu arkasından sürükleyen lider, şef."),
    ("ÖNERİ", "Bir sorunu çözmek için sunulan teklif, tavsiye."),
    ("ÖNLEM", "Kötü ve tehlikeli bir sonucu baştan engellemek için alınan tedbir."),
    ("ÖRÇEN", "Küçük kuşların veya bazı sürüngenlerin adı."),
    ("ÖRDEN", "Sıra, diziliş, nizam anlamına gelen bir kelime."),
    ("ÖRTÜ", "Eşyaların, yatakların üzerine serilen bez veya dokuma malzemesi."),
    ("ÖRÜMCEK", "Ağ örerek avlanan sekiz bacaklı küçük eklembacaklı canlı."),
    ("ÖYKÜ", "Romanlara göre daha kısa olan gerçek/kurgu edebi yazı ürünü, hikâye."),
    ("ÖZGÜN", "Başka hiçbir esere benzemeyen, kopyalanmamış orijinal eser veya kişi."),
    ("ÖZGÜRLÜK", "Herhangi bir kısıtlamaya veya zorlamaya bağlı kalmama hali, hürriyet."),
    ("ÖZLEM", "Bir şeye, sevilen kişiye veya yere karşı duyulan kuvvetli görme ve kavuşma isteği, hasret."),
    ("ÖZNEL", "Nesnel olmayan, kişiden kişiye göre değişen ve sadece birenci ilgilendiren fikir, subjektif."),
    ("PABUÇ", "Ayağa giyilen dayanıklı, kapalı dış giyim, ayakkabı."),
    ("PAÇAVRA", "İyice eskimiş, yıpranmış bez veya değersiz görülen kimse nesne."),
    ("PADİŞAH", "Osmanlı imparatorluğunda devleti yöneten en üst hükümdar ve lider."),
    ("PAHA", "Bir malın ölçülen değer fiyatı veya eşyaya verilen kıymet."),
    ("PAKET", "İçine küçük eşya konularak kâğıda sarılmış kutu."),
    ("PALA", "Kısa, enli ve genellikle eğri kılıç türü veya bıyık türü."),
    ("PALTAR", "Yük taşımakta kullanılan aba veya hasır çuval (eski tabir)."),
    ("PALTO", "Kış aylarında soğuktan korunmak için elbiselerin üzerine giyilen kalın pardösü."),
    ("PANİK", "Aniden gelişen büyük korku, ürküntü ve dehşet halinin bedensel tepkisi."),
    ("PANKART", "Mitinglerde bir sloganın veya tepkinin bez veya mukavvaya yazılmış büyük hali."),
    ("PANTOLON", "Belden başlanarak ayak bileğine veya dize kadar inen, iki paçalı bacak giysisi."),
    ("PAPAĞAN", "Sıcak iklimlerde yaşayan, parlak tüylü ve insan sesini uzun uzun taklit edebilen kuş."),
    ("PAPATYA", "Ortası sarı, kenarları ince beyaz yapraklı ilkbahar çiçeği."),
    ("PARA", "Devletçe basılan, satın alma gücü olarak kabul edilen metal veya kâğıt değişim aracı."),
    ("PARAGRAF", "Düzyazıda kendi içinde bir bütünlüğü olan satırbaşı ile ayrılmış bölüm."),
    ("PARLAK", "Gelen ışığı yansıtan, temiz yüzeyden dolayı parıldayan veya geleceği çok başarılı olacak kişi."),
    ("PARMAK", "İnsanlarda her elde ve her ayakta beş tane olan tutma kızağı uzuvları."),
    ("PAROLA", "Sadece askerlerin vb belli bir grubun birbirini tanımak için kullandığı gizli ve gizemli söz, şifre."),
    ("PARTİ", "Siyasi görüşlerini devlette hakim kılmak isteyenlerin teşkilatı veya yapılan eğlenceli toplantı."),
    ("PASAJ", "Üstü kapalı, içinde dükkanlar bulunan çarşı sokağı veya yazıdan alınan parça (bölüm)."),
    ("PASAPORT", "Kendi devleti tarafından vatandaşına yabancı ülkelere gitmesi iznini vizeleyen yasal kitapçık belge."),
    ("PASTA", "Genellikle kremalı, çikolatalı ve meyveli olarak doğum günlerinde yapılan özel tatlı çeşidi."),
    ("PAZAR", "Haftanın yedinci ve son dinlenme (tatil) günü veya sebze/meyve kurulan alışveriş meydanı."),
    ("PERDE", "Pencereden dışarının görünmesini ve ışığı engellemek için kullanılan tül veya kalın kumaş örtü."),
    ("PERGEL", "Çember çizmek veya küçük mesafeleri ölçmek için kullanılan birleştirilmiş iki ayaklı çizim aleti."),
    ("PERİ", "Masallarda dişi olan, güzellik ve iyilik sembolü olan hayali varlık."),
    ("PERŞEMBE", "Haftanın dördüncü, çarşamba ile cuma arasında kalan günü."),
    ("PİLOT", "Teyyare, helikopter gibi sivil ve askeri hava araçlarını kullanan deneyimli hava şoförü."),
    ("PİRE", "İnsanın vb canlıların kanını emerek beslenen ve vücut ağırlığının çok çok üstünde zıplayan küçük kanatsız böcek."),
    ("PİŞMANLIK", "Yapılan yanlış bir işin veya günahın sonrasında bedel ödercesine çekilen ağır ruhi iç sızısı, nedamet."),
    ("PİYANGO", "Bilet satın alarak kazananın rastgele büyük ödüller aldığı kumar / çekiliş organizasyonu (şans oyunu)."),
    ("PİYAS", "Gösterişli, etrafta çalım satarak kabadayı bir edayla gezinme (özellikle Karadeniz/argo tabiri)."),
    ("POLİS", "Halkın kent içi güvenliğini, asayişini, düzeni sağlayan ve devleti temsil eden silahlı resmi memur."),
    ("PORSELEN", "Beyaz, saydam veya yarısaydam seramik hammaddesi ve bundan yapılan kırılgan çok şık fincan, tabak (özel topraktan)."),
    ("PORTAKAL", "Turunçgillerden; C vitamini kaynağı, kış aylarında yetişen, turuncu ve sulu bir kabuklu ekşimsi meyve."),
    ("PROTEİN", "Hücre inşasında gerekli olan aminoasitlerin büyük yapılı organik biyolojik polimer molekülü."),
    ("PSİKOLOJİ", "İnsan ve diğer canlıların davranışlarını, duygu ve düşüncelerini inceleyen davranış ve ruh bilimi."),
    ("PUSULA", "Kuzeyi ve diğer yönleri sürekli ve doğru biçimde manyetizma ile işaret ederek bulan eski ve güvenilir navigasyon aleti."),
    ("PUT", "İlkel dinlerde (putperestlik) doğaüstü güçleri olduğuna veya tanrı sayıldığına inanılan genelde taş, ağaç (heykelcik) sembol."),
    ("RADYO", "Elektromanyetik dalgalarla havadan alınan sinyalleri yakalayıp, bunları işleyerek hoparlörlere veya kulaklığa ses olarak iletme cihazı."),
    ("RAHNE", "Gedik, bina duvarında vs açılmış tahrip edilmiş yırtık, bozukluk (eski dil)."),
    ("RAMAZAN", "Hicri takvimin dokuzuncu ayı olan ve dinen Müslümanlarca şafaktan gün batımına değin oruç ibadeti yapılan oruç ayı."),
    ("RAPOR", "Herhangi bir hastalık vb mazeret halinde veya araştırma sonuçlandığında amire/idareye sunulan detaylı resmî netice belgesi."),
    ("RASAT", "Gökyüzü hareketlerini, hava olaylarını planlı bir biçimde aletlerle veya çıplak gözle izleyip inceleme faaliyeti, gözlem."),
    ("REÇETE", "Hastanın tedavisinde kullanması adına yetkili uzman hekimin imzalayarak eczaneye alması için hazırladığı imzalı ilaç pusulası."),
    ("REHİNE", "Fidye veya belirli bir amaca ulaşmak için baskı unsuru olarak yasa dışı ve zor kullanılarak el konulup hürriyeti kısıtlanan savaşçı/sivil esir kimse."),
    ("REKABET", "İki kişi, kurum veya takım arasında ticari veya sportif alanda daha iyi olma vb ortak amacı ele geçirmek için gösterilen karşılıklı üstünlük yarışı."),
    ("REKLAM", "Radyo, TV veya bilboardlar aracılığı ile bir ürün veya pazarın ticari anlamda markasını tanıtıp, sattırmak için oluşturulan her türlü kampanyalı duyuru ilanı."),
    ("RESSAM", "Sanatsal içgüdüleri, teknik fırça yetenekleri olan tuval veya herhangi bir zemine boyalarla tablo, duvar sanatı çizen yapan sanatçı sanatkâr şahıs."),
    ("REST", "Pokerde oyuncunun, önündeki fiş/paranın tümünü ortaya koyarak oyundaki büyük bahisleri karşıladığı hamle ve genel argoda boyun eğmemek, oyunu göğüslemek."),
    ("RESTORAN", "Aşçısı, hizmet elemanı, lüks atmosferi olan, sipariş üstüne kaliteli yemek pişirilip parası (hesabı) nakdi ödenen saygın yeme içme veya lokanta tesisi."),
    ("RİTİM", "Şiir ve müzik vb sanatlarda belirli bir vuruş süresinde ardışık eşit olarak veya hecelerin ahengine uygun ahenkli bir vurgu sistemini tanımlamak için müzikal vurumlu dizgesi."),
    ("ROBOT", "Çeşitli akıllı otomatik fonksiyonlara göre iş görebilsin diye programlanarak veya uzaktan direktiflerle idare edilen tasarlanmış yapay ve elektro-mekaniki insanvari makine."),
    ("ROMAN", "Gerçek veya yaşanması kuvvetle muhtemel olan hadiseleri ele alan veya uzun uzun hikaye edilen tasvir karakter ve zaman/zemin betimlemeleri olan olay anlatımlı edebi yazım (eser)."),
    ("ROTASYON", "Kadrolu bir devlet dairesinde vb kurumda kişilerin süre sınırı gelince birim veya bölgelerarası değişikliğe, nöbete tabi, mecbur tutulması durumu (yer değiştirmesi oyunu vb)."),
    ("RÖMORK", "Traktör veya tır arkasına takılıp, motoru ve direksiyonu olmayan ama o araçla yükün çekildiği tekerlekli araba, bir nevi ek taşıma trene benzer kargo römork aracı."),
    ("RÖPORTAJ", "Yaza, sunucu, gazeteci elamanının veya TV reporterin, meşhur bir uzmanı sorguya çekmesi veya halkın düşüncelerini alarak kayıt yapması (Mebuslar-mülakata alınan basın haberi)."),
    ("RÜZGAR", "Atmosfer basınca farkından ötürü oluşarak yatay/dikey bir şekilde yüksekten alçağa havanın hızla şiddetli akımı hareketi durumu olayının bütünü olan havanın hava esmesi (yel)."),
    ("RÜYA", "Uyku (REM evresinde) esnasında iken, beyin kıvrımlarında kendiliğinden doğan görsel veya işitsel tüm sanrılar ve olaylar (daha ulvi manada müjdeleyen görü veya düş dünyası vb) olgusu."),
    ("RIZIK", "İslam inancına veya teolojik kavramlara dayanarak: yaratıcının yarattığı tüm kul ve vahşi varlılara bahşettiği her türlü maddi / manevi gıda ile faydalar veya tüm hayat nimetleri taksimatı."),
    ("RÜŞVET", "Yolsuzluk amaçlı, usulsüz veya memurun yaptırımı gereken işini yaptırmaması uğruna karşılıklı tarafları mutlu kılan parasal/çıkara dayalı gizli yasak para verme, kayırma anlaşması suçu faaliyeti."),
    ("RÜTBE", "Askeri, siyasi ve güvenlik gibi resmi dairesinde çalışan kimselerin devlet protokollerinde hangi kıdemde, aşamada veya rütbede çalıştığını ve statüsünü belirtmek için verilmiş apolet ve mevkisi."),
    ("RANDEVU", "Karşılıklı görüşmek için daha önce belirlenmiş belirli saatli mekân buluşması.")
]


count = 0
next_id = len(db) + 1

for ans, clo in new_words:
    ans_upper = ans.upper().replace('İ', 'I')
    if ans_upper not in existing_words and 5 <= len(ans_upper) <= 13:
        diff = "medium" if len(ans_upper) <= 6 else "hard"
        level = random.randint(3, 5) if diff == "medium" else random.randint(6, 9)
        db.append({
            "id": f"tr_kw_{next_id:04d}",
            "type": "crossword_clue",
            "difficulty": diff,
            "level": level,
            "answer": ans_upper,
            "answerLength": len(ans_upper),
            "category": "Genel Kültür",
            "clue": clo,
            "tags": [f"{len(ans_upper)}-harf", "orta" if diff=="medium" else "zor", "genel", "yeni-sorular-tdk"],
            "createdAt": "2026-02-25"
        })
        existing_words.add(ans_upper)
        next_id += 1
        count += 1

with open(db_path, "w", encoding="utf-8") as f:
    json.dump(db, f, indent=2, ensure_ascii=False)

print(f"Added {count} extremely high quality manual dictionary words to the DB.")
