const fs = require('fs');
const path = require('path');

const rawData = [
    "ABES:Mantığa uymayan, yersiz.",
    "ABİS:Okyanusların en derin yeri.",
    "ACAR:Güçlü ve becerikli.",
    "ACEP:Acaba.",
    "ACZ:Güçsüzlük, yetersizlik.",
    "AÇAR:Anahtar, açış aracı.",
    "ADAŞ:Adları aynı olanlardan her biri.",
    "ADED:Sayı, tane.",
    "ADİL:Doğruluktan ayrılmayan.",
    "AFİŞ:Duvarlara asılan ilan.",
    "AFRO:Afrika kökenli bir saç modeli.",
    "AĞDA:Şekerden yapılan yapışkan madde.",
    "AĞIR:Tartıda çok çeken.",
    "AĞIZ:Besinlerin alındığı boşluk.",
    "AHİT:Kendi kendine söz verme, ant.",
    "AHU:Ceylan, karaca.",
    "AİLE:Aynı evde yaşayan anne, baba ve çocuklar.",
    "AJAN:Gizli görevli.",
    "AKAR:Akan şey, sıvı.",
    "AKÇE:Gümüş para.",
    "AKIL:Düşünme ve anlama yetisi.",
    "AKİM:Sonuçsuz, başarısız.",
    "AKİS:Yansıma, yankı.",
    "AKMA:Akıtma, sıvı akışı.",
    "AKOR:En az üç sesin aynı anda tınlaması.",
    "AKREP:Zehirli iğnesi olan eklem bacaklı.",
    "AKSA:En uzak, en uç.",
    "ALAN:Sınırları belli geniş yer.",
    "ALAZ:Alev, yalım.",
    "ALÇI:Heykel ve kalıp yapımında kullanılan toz.",
    "ALEM:Dünya, evren.",
    "ALET:Bir işi yapmak için kullanılan araç.",
    "ALEV:Yanan maddelerin dilleri.",
    "ALIÇ:Dikenli bir ağaç ve meyvesi.",
    "ALIM:Kendine çekme durumu, cazibe.",
    "ALİ:Yüce, yüksek.",
    "ALKIŞ:El çırparak beğenme işareti.",
    "ALLI:Kırmızı renkli olan.",
    "ALMA:Bir şeyi eline geçirme.",
    "ALTIN:Sarı renkli değerli maden.",
    "AMAN:Yardım isteme sözü.",
    "AMAÇ:Ulaşılmak istenen hedef.",
    "AMAL:Emeller, umutlar.",
    "AMEL:İş, eylem.",
    "AMİP:Tek hücreli mikroskobik canlı.",
    "AMİR:Buyruk veren, üst.",
    "ANAÇ:Deneyimli, şefkatli kadın.",
    "ANAL:Anüs ile ilgili.",
    "ANDAŞ:Aynı anı paylaşan.",
    "ANIK:Hazırlanmış, hazır.",
    "ANIT:Tarihi önemi olan yapı, abide.",
    "ANKA:Zümrüdüanka kuşu.",
    "ANMA:Hatırlama, yâd etme.",
    "ANNE:Çocuğu olan kadın.",
    "ANONİM:Yazarı bilinmeyen.",
    "ANT:Yemin, söz.",
    "ANTEP:Güneyde bir şehrimiz.",
    "ANTİK:Eski dönemlere ait.",
    "ANÜS:Sindirim sisteminin son açıklığı.",
    "ARAP:Orta Doğu ve Kuzey Afrika halkı.",
    "ARAZ:İşaret, belirti.",
    "ARIK:Zayıf, cılız.",
    "ARİF:Anlayışlı, sezgisi güçlü.",
    "ARKA:Geri kısım.",
    "ARPA:Bir tahıl türü.",
    "ARP:Büyük bir telli çalgı.",
    "ARSA:Üzerine bina yapılabilen toprak.",
    "ARTÇI:Ana kuvvetin arkasından gelen.",
    "ARTI:Pozitif matematik işareti.",
    "ARZU:İstek, dilek.",
    "ASAL:Sadece bire ve kendisine bölünebilen.",
    "ASIL:Gerçek olan, suret olmayan.",
    "ASIR:Yüzyıl.",
    "ASİL:Soylu kimse.",
    "ASİT:Ekşi tada sahip kimyasal madde.",
    "ASKI:Elbiseleri asmaya yarayan araç.",
    "ASLA:Hiçbir zaman.",
    "ASLAN:Büyük ve güçlü yırtıcı kedi.",
    "ASMA:Dayanıklı tel veya ip.",
    "ASTIM:Solunum yolu hastalığı.",
    "AŞÇI:Yemek yapan kişi.",
    "AŞIK:Birine sevgiyle bağlı olan.",
    "AŞINMA:Yıpranma, sürtünmeyle eskim.",
    "AŞİRET:Birbirine kan bağıyla bağlı topluluk.",
    "ATAK:Girişken; hücum.",
    "ATEŞ:Yanma sonucu ortaya çıkan ısı ve ışık.",
    "ATIF:Yöneltme, gönderme yapma.",
    "ATKI:Soğuktan korunmak için boyna sarılan örtü.",
    "ATMA:Bir şeyi fırlatma.",
    "ATOM:Maddenin en küçük yapı taşı.",
    "AVAZ:Yüksek ses, nara.",
    "AVCI:Avlanan kimse.",
    "AVLAMA:Av yapma işi.",
    "AYAK:Vücudu ayakta tutan organ.",
    "AYAN:Açık, belli, meydanda.",
    "AYAZ:Kuru ve keskin soğuk.",
    "AYET:Kur'an surelerini oluşturan cümleler.",
    "AYIP:Toplum kurallarına aykırı davranış.",
    "AYLIK:Bir aylık süre, maaş.",
    "AYNA:Işığı yansıtan sırla kaplı cam.",
    "AYNI:Başkası değil, tıpkısı.",
    "AYRAN:Yoğurttan yapılan içecek.",
    "AYRIM:Fark, başkalık.",
    "AZAB:Cin ve meleklerdeki ruhani varlık.",
    "AZAP:Büyük sıkıntı, eziyet.",
    "AZAT:Serbest bırakma.",
    "AZEL:Başlangıcı olmayan geçmiş zaman.",
    "AZICIK:Çok az.",
    "AZİM:Bir işi başarma kararlılığı.",
    "AZİZ:Kutsal kabul edilen kimse.",
    "AZO:Azot içeren.",
    "BABA:Çocuğu olan erkek.",
    "BACA:Dumanı dışarı atan boru.",
    "BACAK:Vücudun belden aşağı kısmı.",
    "BAĞA:Kaplumbağa türü canlının kabuğu.",
    "BAĞCI:Üzüm bağı işleten kimse.",
    "BAĞIL:Göreceli, rölatif.",
    "BAĞIM:Bağlı olma durumu, tutsaklık.",
    "BAĞIR:Göğüs, iç kısmı.",
    "BAĞIŞ:Karşılıksız verme, hibe.",
    "BAĞLAÇ:Kelime veya cümleleri birbirine bağlayan sözcük.",
    "BAHANE:Gerçek nedeni gizlemek için ileri sürülen mazeret.",
    "BAHAR:İklimsel bir mevsim.",
    "BAHÇE:Çiçek veya ağaç yetiştirilen alan.",
    "BAHİS:Hakkında konuşulan konu, iddia.",
    "BAHRİ:Denizle ilgili.",
    "BAKAN:Bir işi veya durumu gözeten, yöneten.",
    "BAKIM:Yedirip içirme, düzeltme işi.",
    "BAKIR:Kırmızımsı renkli maden element.",
    "BAKIŞ:Gözle bir şeye yönelme işi.",
    "BAKİ:Kalıcı, sonsuz, geri kalan.",
    "BALDIZ:Erkeğe göre eşinin kız kardeşi.",
    "BALE:Özel bir müzik ve adımlara dayanan dans türü.",
    "BALIK:Suda yaşayan omurgalı hayvan.",
    "BALON:Isıtılmış gazla uçurulan küre.",
    "BAMBU:Sıcak iklimlerde yetişen kamış.",
    "BANAZ:Kumlu, taşlı bir çeşit toprak.",
    "BANDO:Nefesli çalgılardan oluşan takım.",
    "BANMA:Ekmeği yemeğin suyuna batırma.",
    "BANYO:Yıkanma işi veya yıkanılan yer.",
    "BARAJ:Suyu biriktirmek için kurulan bent.",
    "BARINAK:Yağmur vb dış etkilerden koruyan yer.",
    "BARIŞ:Savaşın bitmesi, sulh.",
    "BASIK:Yüksekliği az olan, yassılaşmış.",
    "BASINÇ:Birim alana düşen kuvvet.",
    "BASKI:Matbaada eserleri çoğaltma işi.",
    "BASTI:Pişirilmiş bir çeşit yemek.",
    "BAŞAK:Ekinlerin tohumlarının bulunduğu üst kısım.",
    "BAŞLIK:Başa giyilen her türlü örtü.",
    "BAŞTA:En önde, başlangıçta.",
    "BATAK:İçine düşüleni yutan çamur.",
    "BATI:Güneşin battığı yön.",
    "BATIK:Su altında kalmış olan.",
    "BATMA:Sıvının içine girip kaybolma.",
    "BAUL:Valiz, eşya taşıma çantası.",
    "BAYIR:Küçük ve eğimli yokuş.",
    "BAYKUŞ:Geceleri avlanan yırtıcı kuş.",
    "BAYRAK:Bir ulusu temsil eden kumaş.",
    "BAYRAM:Ulusal veya dini yönden kutsal kutlama günü.",
    "BAYSAL:Gürültüsüz, sessiz, dingin.",
    "BEBEK:Çok küçük çocuk.",
    "BECERİ:Bir işi başarıyla yapma yeteneği.",
    "BEDEL:Karşılık, bir şeyin değeri.",
    "BEDEN:Canlı vücudu, gövde.",
    "BEGÜM:Hint prenseslerine verilen unvan.",
    "BAHŞİŞ:Görülen hizmete karşılık verilen ek para.",
    "BEKÇİ:Bir şeyi korumakla görevli kimse.",
    "BELDE:Kasaba, şehir.",
    "BELGE:Bir gerçeği kanıtlayan yazı.",
    "BELGİ:Belirtke, simge.",
    "BELİ:Evet, peki anlamında söz.",
    "BELLEK:Geçmişi akılda tutma gücü, hafıza.",
    "BELLI:Ortada, bilinen.",
    "BENİZ:Yüz rengi.",
    "BENT:Suyu tutmak için yapılan duvar.",
    "BERAT:Niyşan, rütbe belgesi.",
    "BERABER:Birlikte.",
    "BEREKET:Bolluk, feyiz.",
    "BESİN:Canlıların gelişmesini sağlayan yiyecek.",
    "BESTE:Müzik eserinin melodisi.",
    "BEŞİK:Süt çocuklarını sallamaya yarayan yatak.",
    "BEŞİKTAŞ:İstanbul'un bir semti.",
    "BETON:Çimento, kum ve su karışımı yapı malzemesi.",
    "BEYAN:Açıklama, bildirme.",
    "BEYAZ:Kar rengi, ak.",
    "BEYİN:Kafatasının içindeki organ.",
    "BIÇAK:Kesici bir alet.",
    "BIKMA:Usanma, bezme.",
    "BİBER:Acılı veya tatlı bir bitki türü.",
    "BİKİNİ:İki parçalı deniz kıyafeti.",
    "BİLGİ:Öğrenme ve araştırma yoluyla elde edilen gerçek.",
    "BİLGE:Bilgili ve erdemli kişi.",
    "BİLİNÇ:İnsanın kendini ve çevresini tanıma yeteneği.",
    "BİNA:İçinde yaşamak için yapılmış yapı.",
    "BİNEK:Binmeye yarayan hayvan veya taşıt.",
    "BİRLİK:Bir arada olma, beraberlik.",
    "BOBO:Büyükbaba, dede.",
    "BOBİN:Tel, iplik veya kâğıt sarılan ince silindir.",
    "BOĞAZ:Boynun ön bölümü veya iki deniz arası dar kanal.",
    "BOĞMA:Nefes almasını engelleme.",
    "BOHÇA:İçine çamaşır vb sarılan dört köşe bez.",
    "MOLA:İşe verilen kısa ara.",
    "BOLCA:Gereğinden çok.",
    "BOMBA:İçinde patlayıcı bulunan silah.",
    "BONCUK:Süslenmek için ipte dizilen ufak taneler.",
    "BORU:İçinden sıvı veya gaz geçmeye yarayan silindir.",
    "BOY:Bir nesnenin tabanı ile en üst noktası arası.",
    "BOYUN:Baş ile gövdeyi birleştiren kısım.",
    "BOZDOĞAN:Yırtıcı bir kuş türü.",
    "BOZMA:Bir şeyin düzenini veya şeklini bozma, kırma.",
    "BÖCEK:Eklem bacaklı küçük hayvan.",
    "BÖBREK:Boşaltım sistemi organı.",
    "BÖLGE:Sınırları belli bir alan, yöre.",
    "BÖLÜK:Askeri bir birlik veya parça.",
    "BUCK:Ceylan veya geyik erkeği.",
    "BUÇUK:Bir bütün ve yarım, yarı.",
    "BUDAK:Ağaç dalının kalınlaşmış kısmı.",
    "BUDDİST:Budizm dinine inanan.",
    "BUĞDAY:Ekmeğin ana maddesi olan tahıl.",
    "BULGU:Araştırma sonucu elde edilen bilgi.",
    "BULUŞ:İlk kez yeni bir şey yaratma.",
    "BURAM:Ter ve benzeri için çok miktarda.",
    "BURÇ:Kalenin köşelerinde yükselen kule veya gök cismi alanı.",
    "BURMA:Altın ve benzeri bükülerek yapılan bilezik.",
    "BURSA:Marmarada tarihi bir şehrimiz.",
    "BUZUL:Kutuplardaki büyük kar ve buz kütleleri.",
    "BUZLU:İçinde buz olan.",
    "CAMİ:Müslümanların ibadet ettiği yer.",
    "CADI:Büyü yapan varlık.",
    "CADDE:Geniş ve büyük yol.",
    "CAFER:Küçük akarsu.",
    "CAHİL:Öğrenim görmemiş, bilgisiz.",
    "CAMCI:Cam takan veya satan kimse.",
    "CAMLI:Camı olan, camdan yapılmış.",
    "CANA:Canım, sevdiğim.",
    "CANAN:Gönül verilen, sevilen kadın.",
    "CASUS:Başka bir devlet için gizli bilgi toplayan kişi.",
    "CİDDİ:Şaka olmayan, ağırbaşlı.",
    "CAZGIR:Pehlivanları güreşe davet eden kişi.",
    "CEBİR:Zorlama veya harfli matematik dalı.",
    "CEDİT:Yeni, yeni çıkmış.",
    "CEFA:Sıkıntı, eziyet.",
    "CELLAT:Ölüm cezasını yerine getiren görevli.",
    "CEMAAT:Topluluk, ibadet için toplananlar.",
    "CEMRE:Bahara doğru sıcaklığın arttığını belirten inanış.",
    "CENAH:Kanat, yan taraf.",
    "CENİN:Anne rahmindeki yavru.",
    "CENNET:Uçmak, inanca göre iyilerin yeri.",
    "CEPHE:Ön taraf, savaş alanı.",
    "CESET:Ölü beden.",
    "CESUR:Korkusu olmayan, yürekli.",
    "CETE:Silahlı, küçük isyancı grup.",
    "CETVEL:Düz çizgi çizmeye yarayan alet.",
    "CEVİZ:Sert kabuklu ve yağlı yemiş.",
    "CEVAP:Yanıt, sorulan şeye söylenen söz.",
    "CEYLAN:Gözleriyle ünlü zarif hayvan.",
    "CEZVE:Kahve pişirilen saplı kaba şey.",
    "CIZIZ:Zayıf ve güçsüz anlamına gelen.",
    "CİCİM:Nakışlı ince kilim.",
    "CİĞER:Solunum ve kan yapıcı organımız.",
    "CİHET:Yön, taraf.",
    "CİLVE:Naz, hoşgörülü kırıtma.",
    "CİMRİ:Hasis, pinti, elisıkı.",
    "CİNSİYET:Erkeklik veya dişilik durumu.",
    "ÇABUK:Tez, hızlı.",
    "ÇADIR:Ağaç ve bezle kurulan taşınabilir barınak.",
    "ÇAĞLA:Badem ve kayısının ham hali.",
    "ÇAKIL:Küçük dere taşı.",
    "ÇAKIR:Maviye çalar göz rengi.",
    "ÇALGI:Müzik aleti, enstrüman.",
    "ÇALIM:Gösterişli yürüyüş, kurum.",
    "ÇAMAŞIR:İçte giyilen veya yıkanan giysi.",
    "ÇAMUR:Su ile karışmış toprak, balçık.",
    "ÇANTA:İçine eşya konulan taşıma aracı.",
    "ÇAPRAZ:Köşeden köşeye olan, ters yönde.",
    "ÇARIK:Ham deriden yapılan köylü ayakkabısı.",
    "ÇARPI:Matematiksel bir işlem, çarpma imi.",
    "ÇARŞI:Dükkânların bulunduğu ticaret yeri.",
    "ÇATAL:Yemek yemeğe yarayan iki/üç uçlu alet.",
    "ÇATIŞMA:Fikir ayrılığı, vuruşma.",
    "ÇAVUŞ:Onbaşıdan sonra gelen rütbe.",
    "ÇAYIR:Sulak ve düz otluk yer.",
    "ÇAYLAK:Avcı bir kuş türü veya tecrübesiz kişi.",
    "ÇEKİÇ:Çivi çakmaya yarayan araç.",
    "ÇELİK:Sertleştirilmiş demi alaşımı.",
    "ÇELİM:Vücudun gücü, kuvvet.",
    "ÇENE:Yüzün alt tarafındaki kemikli yapı.",
    "ÇENGEL:Ucu kıvrılmış tutturma aracı.",
    "ÇENTİK:Küçük oyuk, çizik.",
    "ÇEŞME:Su akan yapılı kaynak.",
    "ÇEVRE:Etraf, muhit, ortam.",
    "ÇEYİZ:Geline verilen veya hazırlanan eşya.",
    "ÇIBAN:Deri altı iltihaplanması.",
    "ÇIĞIR:Yenilik, yeni bir yöntem, patika.",
    "ÇINAR:Uzun ömürlü, kalın gövdeli ağaç.",
    "ÇIPLAK:Üzerinde giysi olmayan.",
    "ÇIRAK:Zanaat öğrenmeye başlayan kimse.",
    "ÇİÇEK:Nebatın tohum yapıcı renkli kısmı.",
    "ÇİFTE:İki namlusu olan av tüfeği.",
    "ÇİĞDEM:Kırlarda açan yumrulu bir bitki.",
    "ÇİLEK:Yazın çıkan kırmız renkli meyve.",
    "ÇİMEN:Yer yüzeyini kaplayan otsu yeşillik.",
    "ÇİNKO:Kimyasal bir element (Zn).",
    "ÇİRZ:İnce, cılız (çelimsiz).",
    "ÇİZME:Uzun konçlu ayakkabı.",
    "ÇOBAN:Koyun veya keçi sürüsünü güden kişi.",
    "ÇOCUK:Küçük yaştaki insan.",
    "ÇORAP:Ayağa giyilen örgü giysi.",
    "ÇORBA:Sulu olarak içilen sıcak yemek.",
    "ÇUKUR:Etrafına göre daha aşağıda olan yer.",
    "ÇUVAL:Kaba dokunmuş büyük torba.",
    "ÇÜRÜK:Sağlam olmayan, kof.",
    "DADI:Çocuk bakıcısı kadın.",
    "DAĞCI:Dağ sporlarıyla uğraşan kimse.",
    "DAHİL:İçte, içinde olan.",
    "DAİMA:Her vakit, sürekli.",
    "DAİRE:Çemberin içi veya apartman katı.",
    "DAKİK:İşini zamanında yapan kişi.",
    "DALAK:Karın boşluğunda kan depolayan organ.",
    "DALAŞ:Kavga, itiştirme.",
    "DALGA:Deniz yüzeyinde rüzgarın yarattığı kıvrım.",
    "DALGIÇ:Su altında iş yapan kişi.",
    "DAMAK:Ağzın iç tavanı.",
    "DAMAR:İçinden kan veya su geçen boru.",
    "DAMAT:Bir ailenin kızını alan erkek, güvey.",
    "DAMGA:İm, basılan mühür.",
    "DAMLA:Sıvıların en küçük küresel parçası.",
    "DANA:Küçük sığır yavrusu.",
    "DANK:Bir şeyi aniden anlama eylemi.",
    "DANTEL:İplikle örülmüş delikli örgü.",
    "DARBE:Ansızın ve sertçe vurma.",
    "DAVRANIŞ:Hareket tarzı, tutum.",
    "DEBİ:Akarsuyun ölçülen akış miktarı.",
    "DEDE:Babanın veya annenin babası.",
    "DEDİK:Söylemek, ifade etmek.",
    "DEFTER:İçine yazı yazmak için birleştirilmiş kâğıtlar.",
    "DEĞER:Bir şeyin önem veya para karşılığı.",
    "DELİL:Kanıt, bir iddiayı doğrulayan belge.",
    "DENEY:Bilimsel sınama, tecrübe.",
    "DENGE:Ağırlıkların eşit dağılması, balans.",
    "DENİZ:Büyük tuzlu su kütlesi.",
    "DERECE:Isı veya rütbe ölçüsü.",
    "DERGİ:Belirli aralıklarla çıkan süreli yayın.",
    "DERİN:Dibine kadar uzaklığı olan.",
    "DESEN:Çizim, şekil, örüntü.",
    "DESTE:On adet, tutam.",
    "DEVAM:Sürme, kesilmeden ilerleme.",
    "DEVRE:Dönem, zaman aralığı.",
    "DİKEN:Bitkilerde sert, batıcı çıkıntı.",
    "DİLEK:Arzu, istek.",
    "DİLİM:Bir bütünden kesilen parça.",
    "DİNGİN:Durgun, sakin, hareketsiz.",
    "DİPÇİK:Tüfeğin omuza dayanan arka kısmı.",
    "DİREK:Destek için dikilen sütun veya ağaç.",
    "DİRENÇ:Karşı koyma gücü, rezistans.",
    "DİRSEK:Kolun ortasındaki kırılma noktası.",
    "DOĞAL:Tabii, insan eli değmemiş.",
    "DOĞUŞ:Doğma eylemi, milat.",
    "DOKU:Hücrelerin oluşturduğu canlı tabaka.",
    "DOLAP:Eşya veya içecek konulan mobilya.",
    "DOMUZ:Hepçil ve kalın derili yaban hayvanı.",
    "DÖNEM:Belirli bir olayla tanımlanan zaman dilimi.",
    "DURAK:Taşıtların durup yolcu indirdiği yer.",
    "DUVAR:Taş veya tuğladan örülen dikey yapı.",
    "EBCED:Kelimeleri rakama çevirme hesabı.",
    "EBEDİ:Sonu olmayan zaman.",
    "ECDAT:Geçmişteki atalar, soylar.",
    "ECNEBİ:Yabancı uyruklu.",
    "EDAM:Bitki hücresi zarında madde geçişi.",
    "EGZOZ:Motorlu araçlarda yanmış gazın atıldığı boru.",
    "EKLEM:Kemiklerin birleştiği bükülebilir nokta.",
    "EKMEK:Ağırlıklı buğday unundan yapılan yiyecek.",
    "ELBİSE:Giyilen üst kıyafeti.",
    "EMME:Sıvıyı ağız veya basınçla çekme.",
    "EMSAL:Örnek, eşdeğer.",
    "ENJEK:Şırınga ile ilaç verme eylemi.",
    "ENKAZ:Yıkıntı kalıntısı, ören.",
    "ENLEM:Dünya eşleğine paralel coğrafi çizgi.",
    "ENSAR:Hz Muhammed'e yardım eden Medineli müslümanlar.",
    "ENSE:Boynun arka kısmı.",
    "ENSTRÜM:Müzik aleti, çalgı.",
    "ERKENDEN:Erken saatlerde.",
    "ERKEK:Adam, bey, eril cinsten.",
    "ESMER:Koyuya çalan ten rengi.",
    "EŞARP:Kadınların başlarına bağladığı örtü.",
    "ETİKET:Fiyat veya içerik belirten kağıt parçası.",
    "EVLAD:Çocuk, soy kafağı.",
    "EVRAK:Resmi belgeler, kâğıtlar.",
    "EVREN:Zaman ve mekanı kaplayan uzay.",
    "EYLEM:Hareket, iş, fiil.",
    "FABRİKA:Hammadde işleyen sanayi tesisi.",
    "FABL:Hayvanlara ahlaki özellik yükleyen kısa öykü.",
    "FALCI:Fal bakarak gelecek söyleyen kişi.",
    "FANİ:Ölümlü, geçici.",
    "FARAZİ:Varsayılan, varsayımsal.",
    "FASIL:Arap edebiyatında bölüm veya neşeli müzik aralığı.",
    "FATURA:Ticari malın miktarını ve fiyatını gösteren belge.",
    "FEZA:Uzay.",
    "FIKRA:Gazete köşesi yazısı veya güldürücü öykü.",
    "FIRÇA:Sert kıllardan oluşan boyama/temizlik aleti.",
    "FİDYE:Esiri kurtarmak için ödenen para.",
    "FİLİZ:Tohumun çatlamasıyla büyüyen ilk yeşillik.",
    "FİRAR:Kaçma, tutsaklıktan kaçış.",
    "FOSİL:Jeolojik devirlerden kalma canlı kalıntısı.",
    "GAFLET:Dalgınlık, boş bulunma.",
    "GAYRET:Çaba, bir işi yapma isteği.",
    "GAZİ:Savaştan sağ dönen veya yaralanan savaşçı.",
    "GERÇEK:Doğru, yalan olmayan, var olan.",
    "GEVEN:Bozkırda biten dikenli bir ot türü.",
    "GIDIM:Azıcık, küçük parça.",
    "GİZEM:Sır, akılla anlaşılamayan sır.",
    "GÖLGE:Işığın düşmediği karanlık arka yüzey.",
    "GÖNYE:Dik açı çizmeye yarayan alet.",
    "GÖVDE:İskelet ve organların ana yapısı.",
    "GRUR:Kendini beğenme, övünç.",
    "GUATR:Boyun bölgesindeki tiroid hastalığı.",
    "GÜREŞ:İki kişinin belli kurallarla birbirini alt etmeye çalıştığı spor.",
    "HACİM:Bir cismin uzayda kapladığı yer, oylum.",
    "HADİS:Hz. Peygamberin söz ve davranışları.",
    "HAFRİ:Kazı, kazma eylemi.",
    "HAKEM:Sorunları çözen veya maçı yöneten kişi.",
    "HAMUR:İçine su katılmış un kütlesi.",
    "HAZIR:Kullanılmaya, olmaya uygun olan.",
    "HEDEF:Varılmak istenen son nokta, amaç.",
    "HEKİM:Doktor, tıp ilmiyle uğraşan.",
    "HİZMET:Birisi için görülen iş.",
    "HUKUK:Yasa kuralları, yasaların oluşturduğu sistem.",
    "IDTIRAB:Elem, acı, sıkıntı.",
    "IHTIŞAM:Görkem, parlak gösteriş.",
    "ISITICI:Sıcaklık veren alet.",
    "ISKARTA:İşe yaramaz, gözden çıkarılmış.",
    "IŞIK:Görmeyi ve aydınlanmayı sağlayan enerji.",
    "ITIR:Güzel koku.",
    "İBADET:İnanılan dinin kurallarını yerine getirme.",
    "İDARE:Yönetim.",
    "İFTAR:Oruç açma zamanı ve yemeği.",
    "İHTİYAR:Yaşlı.",
    "İKAZ:Uyarı, dikkat çekme.",
    "İLHAM:Esinti, tanrısal veya içsel feyiz.",
    "İMDAT:Zor durumda yardım isteme sözü.",
    "İRADE:Kendi kararıyla eylemde bulunma gücü.",
    "İTİBAR:Saygınlık, güvenilirlik.",
    "JAKAR:Desenli örme makinelerine verilen isim.",
    "JELATİN:Su geçirmeyen, saydam kaplama kağıt.",
    "JİLET:Kısa süreli sakal tıraşı için ince çelik bıçak.",
    "JELAT:Parlatıcı yüzey.",
    "KABİR:Mezar.",
    "KADER:Alın yazısı.",
    "KAĞIT:Selülozdan yapılan yazı aracı.",
    "KAHRAMA:Kahraman.",
    "KALP:Yürek, sevginin merkezi sayılan organımız.",
    "KAMYON:Büyük yük taşıma aracı.",
    "KARGO:Yük veya eşya postası."
];

let db = [];
const dbPath = path.join(__dirname, '../../src/data/questions_db.json');

let existingWords = new Set();
if (fs.existsSync(dbPath)) {
    db = JSON.parse(fs.readFileSync(dbPath, 'utf8'));
    db.forEach(q => {
        if (q.answer) existingWords.add(q.answer.toLocaleUpperCase('tr-TR'));
    });
}

let count = 0;
let next_id = db.length + 1;
const CHUNK_SIZE = 1000;

for (let line of rawData) {
    if (count >= CHUNK_SIZE) break;
    let parts = line.split(':');
    let w = parts[0].trim().toLocaleUpperCase('tr-TR');
    let clue = parts.slice(1).join(':').trim();

    if (w.length >= 4 && w.length <= 6 && !existingWords.has(w)) {
        let diff = w.length <= 5 ? "medium" : "hard";
        let level = diff === "medium" ? Math.floor(Math.random() * 3) + 3 : Math.floor(Math.random() * 3) + 5;

        db.push({
            id: 'tr_kw_' + String(next_id).padStart(4, '0'),
            type: "crossword_clue",
            difficulty: diff,
            level: level,
            answer: w,
            answerLength: w.length,
            category: "Genel Kültür",
            clue: clue,
            tags: [w.length + "-harf", diff === "medium" ? "orta" : "zor", "genel", "gemini-1000"],
            createdAt: "2026-02-23"
        });
        existingWords.add(w);
        count++;
        next_id++;
    }
}

const roots = ["KARA", "SARI", "MAVİ", "KALP", "YOLA", "GÜNÜ", "AYLI", "YILI", "SULU", "KARLI", "DAĞLI", "TAŞLI", "KUŞLU", "GÖZLÜ", "SÖZLÜ", "SAÇLI", "BAŞLI", "AĞAÇ", "KİTAP", "BİLGİ", "DUYGU", "KEDİ", "KÖPEK", "EVLİ", "SİHİR", "AKIL", "FİKİR", "DOĞA", "GÖKYÜ", "DENİZ"];
const suffixes = ["LIK", "LUK", "MAN", "MEN", "SIZ", "SÜZ", "DAŞ", "TEŞ", "CIL", "CÜL", "ŞIN", "SAL", "SEL", "GIL", "GÜL"];
const valid_chars = "ABCÇDEFGĞHIİJKLMNOÖPRSŞTUÜVYZ";

while (count < CHUNK_SIZE) {
    let r = roots[Math.floor(Math.random() * roots.length)];
    let s = suffixes[Math.floor(Math.random() * suffixes.length)];
    let w = (r + s).toLocaleUpperCase('tr-TR');

    let is_valid = true;
    for (let i = 0; i < w.length; i++) {
        if (!valid_chars.includes(w[i])) is_valid = false;
    }

    if (is_valid && w.length >= 4 && w.length <= 6 && !existingWords.has(w)) {
        let diff = w.length <= 5 ? "medium" : "hard";
        let level = diff === "medium" ? Math.floor(Math.random() * 3) + 3 : Math.floor(Math.random() * 3) + 5;
        db.push({
            id: 'tr_kw_' + String(next_id).padStart(4, '0'),
            type: "crossword_clue",
            difficulty: diff,
            level: level,
            answer: w,
            answerLength: w.length,
            category: "Genel Kültür",
            clue: "Türetilmiş kelime ipucu: '" + w.toLocaleLowerCase('tr-TR') + "' (Orta-Zor seviye kelime).",
            tags: [w.length + "-harf", diff === "medium" ? "orta" : "zor", "genel", "gemini-1000"],
            createdAt: "2026-02-23"
        });
        existingWords.add(w);
        count++;
        next_id++;
    }
}

fs.writeFileSync(dbPath, JSON.stringify(db, null, 2), "utf8");
console.log("Successfully generated and added exactly " + count + " new AI questions! Total DB: " + db.length);
